### ISSUE TITLE
[polymer-project-config] Add field for files/directories to ignore when linting

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#106]
*Originally posted at Fri, 31 Mar 2017 16:32:24 GMT at https://github.com/Polymer/polymer-project-config/issues/11*

**Comment by rictic** [comment]
Looks right. Still need to hook it up in WarningFilter and in the CLI.

*Originally posted at Tue, 06 Mar 2018 19:43:21 GMT at https://github.com/Polymer/polymer-project-config/issues/11#issuecomment-370903561*

**Comment by alvardsoler** [comment]
what about this?
this isn't working for me with this configuration:
`  "lint": {
    "filesToIgnore": ["dist/**/*"],
    "rules": ["polymer-1"],
    "ignoreWarnings": [
      "databind-with-unknown-property",
      "undefined-elements"
    ]
  },`
I tried to find other issue but this a little confusing...
