### ISSUE TITLE
Extending polyserve server

### ISSUE THREAD

**Issue by jlndk** [Polymer/tools#1077]
In my latest project i found the need to extend polyserve, with extra routes. I think it would be a really valuable tool, when you develop polymer elements, that depends on some backend techologies, like WebSocket.

I found out that this could easily be done, by returning the server variable from the startServer() function. It's an easy fix, that would make development so much easier.

**Comment by mercmobily** [comment]
I know this is a closed issue on a barely supported file, but... I had no luck with `makeApp`. What worked for me, perfectly, was `getApp()`
If I use makeApp, I am getting a resounding "undefined"
I am doing this:

````
var startServer = require('polyserve/lib/start_server.js')

// .. various routes in my application, and then...

if (process.env.NODE_ENV === 'development' || !process.env.NODE_ENV){
  var polyserveApp = startServer.getApp({
    moduleResolution: 'node',
    npm: true,
  })
  app.use(polyserveApp)
} else {
  var prplHandler = prpl.makeHandler('build', polyConfigFile)
  app.get('/*', (req, res, next) => { prplHandler(req, res, next) })
}
````

This means that in development I use polyserve, which is awesome AND -- more importantly -- it resolves module names correctly.

I can't imagine why this is not documented. Anybody who works on a project based on the PSK is expected to wait 30 seconds to build their software, before they can test every tiny change?

Doesn't this need to be documented?

**Comment by mercmobily** [comment]
@justinfagnani I know you are probably busy with more important stuff, but your input of this would be very beneficial. Would you support a PR that adds this to the docs? Plus can you confirm my suspicion -- that `makeApp` is not the way to go, and `getApp`  is?

**Comment by krumware** [comment]
This is just what I was looking for. It would be great if this was documented!

**Comment by krumware** [comment]
Worked like a charm. Here is the source location for additional options: https://github.com/Polymer/tools/blob/01265ce15c2ec86f688c3bfe6f39faefc277f914/packages/polyserve/src/start_server.ts#L40

**Comment by mercmobily** [comment]
This is a buried helpful thing in a buried closed issue. Which is a shame. It will hopefully grab the attention of a core developer.
