### ISSUE TITLE
[Feature Request] Add -x option allowing files to be excluded from shared bundle

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#1190]
This feature is implemented in following [web-component-shards](https://github.com/PolymerLabs/web-component-shards/pull/15) PR.

`exclude` could be very useful option. It would allow us to generate separate bundle containing some deps, and to exclude those deps from `shared-bundle.html` used by page bundles.

Example cases:
1.  Exclude `font-roboto` import into a separate bundle and load it as fast as possible.
2. Load some dependencies from app-shell (separate) and then each page load `shared-bundle.html` + page level dependencies.

**Comment by web-padawan** [comment]
The original case for this issue was to "extract Polymer itself into a shared chunk". In that project where I used to work, we ended up with using `generateSharedDepsMergeStrategy()`.

This is something that might be possible in future with webpack 5 and [module federation](https://dev.to/marais/webpack-5-and-module-federation-4j1i).

**Comment by ScriptedAlchemy** [comment]
Message me if you have any question on module federation
