### ISSUE TITLE
Bundling in Node.js not working

### ISSUE THREAD

**Issue by shaji-Dev** [Polymer/tools#123]
Hi,

I've been trying to bundle the HTML programmatically in Node.js following the example but the result content is always undefined.

const bundler = new require('polymer-bundler').Bundler();
bundler.generateManifest(['my-app.html']).then((manifest) => {
bundler.bundle(manifest).then((result) => {
console.log(result.documents.get('my-app.html').content));
});
});

This prints 'undefined'. If I remove the .content, I get this:
{
ast:
{ nodeName: '#document',
quirksMode: false,
childNodes: [ [Object], [Object] ] },
files:
[ ..... ]
}

Am I doing anything wrong?

**Comment by justinribeiro** [comment]
Saw a similar issue a few days ago. If we take a peek at `html-bundler.ts`, we see that on line 94 content is output via serialising the AST. https://github.com/Polymer/tools/blob/c9391e3c0c06f897296332d001ae3c2e07ff1529/packages/bundler/src/html-bundler.ts#L94

We can write a slightly modified example that will produce similar results by doing this ourself:

```js
const {Bundler} = require('polymer-bundler');
const parse5 = require('parse5');
const bundler = new Bundler();

bundler.generateManifest(['my-app.html']).then((manifest) => {
  bundler.bundle(manifest).then((result) => {
    console.log('<!-- BUNDLED VERSION OF my-app.html: -->');
    for (const [url, document] of result.documents) {
      if (!document.content) {
        console.log(parse5.serialize(document.ast))
      } else {
        console.log(document.content);
      }
    }
  });
});```

**Comment by shaji-Dev** [comment]
I eventually encountered the same solution, that's great, thank you very much.
