### ISSUE TITLE
[polyserve] 0.27.6 modules with .js extension are not resolved if importing by absolute path

### ISSUE THREAD

**Issue by mkorenko** [Polymer/tools#126]
Using --module-resolution "node":

`import {SomeService} from '../services/some.service'` - works (relative path, no extension)

`import {SomeService} from '/src/services/some.service.js'` - works (absolute path, with extension)

`import {SomeService} from '/src/services/some.service'` - 404 (absolute path, no extension)

Expected: .js extension should be auto-resolved when using absolute path module identifier.

polyserve: 0.27.4
node: 9.11.1
os: macos

**Comment by web-padawan** [comment]
Might be the same as #9

**Comment by mkorenko** [comment]
@web-padawan might be related, as you get 404 depending on path, but I'm not sure.
This issue is about absolute path identifiers.

**Comment by mkorenko** [comment]
0.27.6 - the issue is still reproduced.
