### ISSUE TITLE
Transform Dynamic import() for ES5 target

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#1311]
This is necessary to support distributing module-based code with dynamic imports to browsers that don't support them, aka Polymer 3.0 based applications!

**Comment by daKmoR** [comment]
is this still unsupported?

**Comment by usergenic** [comment]
I'm fairly certain this bug is not relevant now that es5 compilation with polymer-build converts imports to use the https://github.com/Polymer/tools/tree/master/packages/esm-amd-loader
