### ISSUE TITLE
Recommendation: Add a note informing about the repository change

### ISSUE THREAD

**Issue by abdonrd** [Polymer/tools#183]
I would like to recommend that you add a note in the GitHub description informing about the repository change. I mean from:

![from](https://user-images.githubusercontent.com/1007051/38977390-92a37888-43b4-11e8-97ca-84d9ed3de1ae.png)

To:

![to](https://user-images.githubusercontent.com/1007051/38977395-94c6f66c-43b4-11e8-921a-52b7d660e704.png)

You could even add the URL in the GitHub URL from:

![from](https://user-images.githubusercontent.com/1007051/38977718-7bfa1d66-43b5-11e8-9a6d-cf2ba4c360d2.png)

To:

![to](https://user-images.githubusercontent.com/1007051/38977722-7e9f5720-43b5-11e8-95de-718d445c7282.png)

Repositories:

* [x] https://github.com/Polymer/polymer-analyzer
* [x] https://github.com/Polymer/browser-capabilities
* [x] https://github.com/Polymer/polymer-build
* [x] https://github.com/Polymer/polymer-bundler
* [x] https://github.com/Polymer/tools-common
* [x] https://github.com/Polymer/polymer-editor-service
* [x] https://github.com/Polymer/polymer-linter
* [x] https://github.com/Polymer/polyserve
* [x] https://github.com/Polymer/polymer-project-config
* [x] https://github.com/Polymer/web-component-tester

**Comment by aomarks** [comment]
Done, thanks for the checklist.

**Comment by abdonrd** [comment]
Thanks @aomarks! 👏  Now I think there will be less confusion about the old repositories!
