### ISSUE TITLE
Build AMD issue

### ISSUE THREAD

**Issue by busynest** [Polymer/tools#186]
When built and deployed:
1. about half the requireJS loads, but breaks at "b.PolymerElement" (to me it seems like a problem with reading class extension "PolymerElement")
2. I also get a 404 on scripts like webcomponents, Thought I fixed with "transformModulesToAmd: true" maybe when I set the script type="text/javascript" it might have helped.

**Comment by aomarks** [comment]
Can you provide some more information about which tools you're using, the exact commands, versions, any info about your code (link if possible). See https://github.com/Polymer/tools/issues/182 for a great example of the kind of format that is most helpful.

**Comment by busynest** [comment]
github.com/busynest/roofing & roofingcontract.com

**Comment by busynest** [comment]
Update:
1. upgrade: Polymer-cli From: pre.10 To: pre.12 = Extension Error still occuring.
2. Fixed: webcomponents load: type="script"

**Comment by aomarks** [comment]
Are you using Polymer 2 or 3? Have you used modulizer to convert your project? Are you using ES modules?

**Comment by aomarks** [comment]
Did you set `--import-style=name`?

See https://github.com/Polymer/polymer-modulizer#conversion-options

**Comment by busynest** [comment]
With the "--import-style=name" flag

`import { Element } from '@polymer/polymer/polymer-element.js';`
new `index.js`

**Comment by busynest** [comment]
When I Polymer Analyze my project: 
```
<--- Last few GCs --->

[9048:000002F49D5CA300]   364110 ms: Mark-sweep 1372.7 (1531.9) -> 1372.5 (1533.4) MB, 4820.8 / 0.2 ms  allocation failure GC in old space requested
[9048:000002F49D5CA300]   369358 ms: Mark-sweep 1372.5 (1533.4) -> 1372.5 (1498.9) MB, 5201.5 / 0.2 ms  last resort GC in old space requested
[9048:000002F49D5CA300]   374489 ms: Mark-sweep 1372.5 (1498.9) -> 1372.5 (1495.4) MB, 5129.7 / 0.2 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003C4C30257C1 <JSObject>
    1: isType(aka isType) [C:\Users\BusyNest\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\@babel\types\lib\validators\isType.js:~10] [pc=0000000259F49BA2](this=0000039A5E4022D1 <undefined>,nodeType=0000019ED47EEDE9 <String[18]: VariableDeclarator>,targetType=0000019ED47EDF41 <String[8]: Scopable>)
    2: checkPath [C:\Users\BusyNest\AppData\Roaming\npm\node_modules\polymer-cli\nod...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewCodeRaw
 5: v8::internal::Factory::NewCode
 6: v8::internal::modulo
 7: v8::internal::compiler::ControlFlowOptimizer::TryBuildSwitch
 8: v8::internal::interpreter::HandlerTableBuilder::HandlerTableBuilder
 9: v8::internal::compiler::Pipeline::AllocateRegistersForTesting
10: v8::internal::compiler::ValueNumberingReducer::operator=
11: v8::internal::CompilationJob::FinalizeJob
12: v8::internal::compiler::SimplifiedOperatorReducer::factory
13: v8::internal::Compiler::FinalizeCompilationJob
14: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions
15: v8::internal::StackGuard::HandleInterrupts
16: v8::internal::wasm::WasmOpcodes::TrapReasonMessage
17: 0000000259E043C1
```

**Comment by busynest** [comment]
so I get two "type" errors
1. From the browser when deployed:
`Uncaught TypeError: Class extends value undefined is not a constructor or null`
&
2. From Polymer Analyze:
`isType(aka isType) [C:\Users\BusyNest\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\@babel\types\lib\validators\isType.js:~10] [pc=0000000259F49BA2](this=0000039A5E4022D1 <undefined>,nodeType=0000019ED47EEDE9 <String[18]: VariableDeclarator>,targetType=0000019ED47EDF41 <String[8]: Scopable>)`

**Comment by busynest** [comment]
In FireFox: App does not work:
`TypeError: window.customElements is undefined[Learn More] settings.js:12:35`
`ReferenceError: customElements is not defined[Learn More] dom-module.js:140:3`

**Comment by busynest** [comment]
So it looks like two kinds of problems to me: a Type Error & Too many properties loaded into a small memory space ??
