### ISSUE TITLE
Cannot proceed after "polymer init"

### ISSUE THREAD

**Issue by lflee** [Polymer/tools#2106]
I try to follow https://www.polymer-project.org/1.0/docs/tools/polymer-cli to create an app project.
But I cannot proceed after `polymer init`. I cannot move to other options by using the Down arrow key. But other init, like `polymer init application` works fine.

I think I has installed the necessary prerequisites - 
![33](https://cloud.githubusercontent.com/assets/3342858/15452861/3f1329ec-2030-11e6-8adf-a8d9e82b1fbc.png)

Is it a bug or I've done something wrong?

**Comment by rveluthattil** [comment]
Am using node version 10.13.0 version of node and version 1.9.5 of polymer. When i give polymer init it tells uname is not found and on choosing polymer-2-application just hangs. When i say polymer init polymer-2-application it asks some questions and then again hangs after accepting brief description of project
![image](https://user-images.githubusercontent.com/16926792/51551370-5980e000-1e3c-11e9-9025-972e436e4453.png)
