### ISSUE TITLE
[wct] Update Mocha

### ISSUE THREAD

**Issue by merlinnot** [Polymer/tools#227]
We should update Mocha version, since it resolves multiple bugs and introduces some new features. It also contains some braking changes, so it requires a major version bump of WCT. Please consult Mocha changelog to learn more.

**Comment by jlaamanen** [comment]
I would like to add that Mocha versions prior to v4 (WCT has ^3.4.2) use growl version 1.9.2, which has a critical vulnerability according to Node security: https://nodesecurity.io/advisories/146. Because of this, `npm audit` fails for projects that have web-component-tester listed as a dependency.
