### ISSUE TITLE
Exceeding memory limit when running polymer lint on a large project

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#2374]
### Description
When running `polymer lint --rules polymer-1` from my project root I see the following error:

```
<--- Last few GCs --->

   93118 ms: Mark-sweep 1365.7 (1407.3) -> 1365.6 (1411.3) MB, 1365.1 / 0.0 ms [allocation failure] [GC in old space requested].
   94569 ms: Mark-sweep 1365.6 (1411.3) -> 1365.6 (1411.3) MB, 1450.8 / 0.0 ms [allocation failure] [GC in old space requested].
   95967 ms: Mark-sweep 1365.6 (1411.3) -> 1374.8 (1407.3) MB, 1397.2 / 0.0 ms [last resort gc].
   97297 ms: Mark-sweep 1374.8 (1407.3) -> 1383.9 (1407.3) MB, 1329.0 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2eec362cfb51 <JS Object>
    2: applyScanners(aka applyScanners) [/Users/sergej/.nvm/versions/node/v6.9.3/lib/node_modules/polymer-cli/node_modules/polymer-analyzer/lib/javascript/javascript-document.js:44] [pc=0x636680398c2] (this=0x2eec36204381 <undefined>,callbackName=0x24b212b89ac1 <String[23]: enterFunctionExpression>,node=0x3398b20afdb9 <a Node with map 0x1e7570d2341>,parent=0x3398b20afd11 <a Node with map 0x1e75...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 5: v8::internal::FullCodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 6: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 7: v8::internal::Compiler::EnsureDeoptimizationSupport(v8::internal::CompilationInfo*) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 8: v8::internal::OptimizedCompileJob::CreateGraph() [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
 9: v8::internal::(anonymous namespace)::GetOptimizedCode(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ConcurrencyMode, v8::internal::BailoutId, v8::internal::JavaScriptFrame*) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
10: v8::internal::Compiler::CompileOptimized(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ConcurrencyMode) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
11: v8::internal::Runtime_CompileOptimized_Concurrent(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/sergej/.nvm/versions/node/v6.9.3/bin/node]
12: 0x636675092a7
[1]    21438 abort      polymer lint -v --rules polymer-1
```

### Versions & Environment

- Polymer CLI: 0.18.0-pre.14
- node: 6.9.3
- Operating System: Max OS El Capitan

Interestingly, running from `src` completes successfully, but I get a bunch of warnings about undefined elements,those are in `bower_components` directory which is one level up and seems not to be resolved (not sure is it worth creating other issue, though).

I have removed `dist` and all temporary directories to prevent scanning them, but with no success. Any suggestions? Known workaround is to run command via `node --max-old-space-size=3072` but it is not how it should like IMO.

**Comment by bastienarm** [comment]
Same problem here since this morning

[8952:0000020F1954BA10]    95246 ms: Scavenge 1317.9 (1436.2) -> 1307.5 (1439.7) MB, 12.6 / 0.0 ms  (average mu = 0.105, current mu = 0.054) allocation failure
[8952:0000020F1954BA10]    95330 ms: Scavenge 1320.5 (1439.7) -> 1309.8 (1442.7) MB, 12.4 / 0.0 ms  (average mu = 0.105, current mu = 0.054) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002909E95C5C1]
Security context: 0x0229fb79e6e1 <JSObject>
    1: word [0000014F23E32009] [C:\Users\Bastien\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\babel-generator\lib\printer.js:~127] [pc=000002909F55D173](this=0x00c5556022c1 <Generator map = 00000039EFE87ED1>,str=0x0122b0fff9c1 <String[5]: value>)
    2: Identifier [0000014D5577EC61] [C:\Users\Bastien\AppData\Roaming\npm\node_modules\polymer-cl...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7DC6FECE5
 2: 00007FF7DC6D8196
 3: 00007FF7DC6D8BA0
 4: 00007FF7DC968D5E
 5: 00007FF7DC968C8F
 6: 00007FF7DCEA69D4
 7: 00007FF7DCE9D137
 8: 00007FF7DCE9B6AC
 9: 00007FF7DCEA4627
10: 00007FF7DCEA46A6
11: 00007FF7DCA47767
12: 00007FF7DCADF44A
13: 000002909E95C5C1


I don't know why, but when changing the head on my git repo and doing a git reset -fd will make the build works sometimes...
