### ISSUE TITLE
polymer build --js-minify does not minify some files

### ISSUE THREAD

**Issue by lawrence9811** [Polymer/tools#2417]
polymer build --js-minify

seems to work with javascript within html files only, but does not minifying standalone .js files, such as:

/bower_components/webcomponentsjs/webcomponents-loader.js

the build is exactly the same as the source, even all comments are intact.

**Comment by RobMaskell** [comment]
@FredKSchott  found this issue after testing my PWA on `https://web.dev` and it's complaining about lack of minification. I realised we can't compile these files but is there a possibility of removing comments and whitespace that might make this pass the tests on `https://web.dev`. I think it's complaining about webcomponents-loader.js
