### ISSUE TITLE
Problems with using the CLI tools on existing projects

### ISSUE THREAD

**Issue by ruphin** [Polymer/tools#2422]
### Description
These are some problems I ran into when using the CLI tools on an existing Polymer project.
For reference, my project source can be found here: https://github.com/ruphin/overwebs/tree/polymer2.0
A recording of my process can be seen here: https://www.twitch.tv/videos/138879292?t=24m11s

#### Polymer Lint
I immediately ran into this issue: https://github.com/Polymer/polymer-analyzer/issues/584
Basically my folder naming scheme doesn't match what Polymer expects it to be, so the tool doesn't work. I tried for a few minutes to ignore the issue and work around it, but I very quickly gave up, the output was unusable in this state.

#### Polymer Build
This was the tool I was most interested in. I currently use a self-authored Gulp build pipeline. My application layout is rather simple: I have a folder for Elements, each Element consists of an HTML file for markup, a JS file for logic, and an SCSS file for styling. My current build pipeline works by processing these files to produce transpiled/minified output, and concatenating them when necessary. Aside from that there is just an index.html entrypoint, and some static assets.

I tried using this as a template for a gulp pipeline using the new tools: https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/master/generators/app/gulpfile.js

The first problem I immediately ran into was an `Error: File not found with a singular glob: /app/index.html`.
It would have saved me 10 minutes if the error message was a bit less cryptic, but I eventually figured out that it expected the entrypoint index.html to be in the app root. Easy enough to fix.
It took me a little while after tha

It would have saved me 10 minutes if the error message was a bit less cryptic, but I eventually figured out that it expected the entrypoint index.html to be in the app root. Easy enough to fix.
It took me a little while after that to fix my relative imports to match the new folder layout. Looking back at it, it is possible that I could have kept my old layout and configured the location of the entrypoint in polymer.json, but I haven't tried.

The next problem was that I couldn't get anything to work with my SCSS files. My current solution to SCSS is an adapted version of https://github.com/superjose/polymer-sass, which means my build pipeline processes the SCSS and inlines it into a 'style-module', which is imported by the main element.
I modified the gulpfile above by passing the SCSS files through node-sass, and renaming the files in the pipe to the proper .css extension, double checked with gulp debug that all files in the pipe were correct, but I couldn't get past `error: [cli.build.analyzer] In src/elements/overwebs-app/overwebs-app.html: [could-not-load] - Unable to load import: Not found: "/app/src/elements/overwebs-app/overwebs-app.css"` I think I gave up after like 30 minutes.

I really love the new tools, I think they provide much needed help in managing frontend projects, and I would love to be able to use them, but issues like these make it really hard to. It feels like unless your project is built from the start with these tools in mind (use the correct folder layouts, naming schemes) and you use no other technologies or languages, they are prohibitively difficult to use. The problem is that you run into some error because your code isn't exactly like the tool expects, and it's effectively impossible to find anything on how to solve the issue. Even though my old handknitted build pipeline is pretty poor compared to the new tools, from a user's perspective it's still easier to write my own tools than to fix yours, which is a shame because I really want to use yours.

**Comment by kevinsimper** [comment]
I have this problem, I want to move my `index.html` into the `src` folder, but when I succeed with that it can't find the `npm` modules. I could move my npm modules inside the source folder, but it would be nice to have it stay in the root.

So going from default:
```
polymer build
```

to moving your index.html to not lie in the root does not seem that possible, if you want to resolve node_modules that are installed at the project root

```
polymer build --entrypoint src/index.html --root src/
# or
polymer build --entrypoint index.html --root src/ --npm --sources "**/*"
```

```
info:	Clearing build/ directory...


import { LitElement, html } from "lit-element";
                                 ~~~~~~~~~~~~~

file:///Users/kevinsimper/my-github-project/src/main.js(1,34) error [could-not-load] - Unable to load import: Not found: /Users/kevinsimper/my-github-project/src/node_modules/lit-element/lit-element.js
```

Here it simply tries to look up the node_modules in the wrong folder, even though the imports referes to straight strings with no paths.

So, the path rewrite is not working that well in the not normal example.
