### ISSUE TITLE
"polymer build" doesn't inject ES5 adapter when bundling

### ISSUE THREAD

**Issue by hormesiel** [Polymer/tools#2486]
### Description
`polymer build` doesn't inject `custom-elements-es5-adapter.js` like expected, as the doc says [here][1] :

`
When you use the Polymer CLI to compile your app, the CLI automatically compiles the correct files and injects custom-elements-es5-adapter.js, a lightweight polyfill that lets compiled ES5 work on browsers that support native custom elements.
`

and [here][2] :

`
The --js-compile flag adds the custom-elements-es5-adapter.js adapter for running ES5 code on browsers that support ES6.
`

[1]: https://www.polymer-project.org/2.0/docs/es6#compile
[2]: https://www.polymer-project.org/2.0/toolbox/build-for-production#compiling

### Versions & Environment

- Polymer CLI: 1.2.0
- node: v7.10.0
- Operating System: Linux Mint 17.3 Rosa

#### Steps to Reproduce

1. Create an `/demo/polymer2.html` file with the following content :

```html
<!doctype html>
<html lang="fr">
  <head>
    <title>polymer2</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">

    <script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
    <link rel="import" href="../src/demo/polymer2-app.html">
  </head>

  <body>
    <polymer2-app></polymer2-app>
  </body>
</html>
```

2. Create a `/src/demo/polymer2-app.html` file with the following content :

```html
<link rel="import" href="../../bower_components/polymer/polymer.html">

<dom-module id="polymer2-app">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <h1>polymer2-app</h1>
  </template>

  <script>
    class Polymer2App extends Polymer.Element {
      static get is() {
        return 'polymer2-app';
      }
    }

    customElements.define(Polymer2App.is, Polymer2App);
  </script>
</dom-module>
```

3. Create a `polymer.json` file with the following content :

```json
{
  "builds": [{
    "bundle": true,
    "css": {"minify": true},
    "html": {"minify": true},
    "js": {"compile": true, "minify": true}
  }],
  "lint": {
    "rules": [
      "polymer-2"
    ]
  }
}
```

4. Build : `polymer build --entrypoint demo/polymer2.html`

#### Expected Results

1. `polymer build` should inject either a `<script src="/bower_components/webcomponentsjs/custom-elements-es5-adapter.js"></script>` or the content of the script directly into the compiled `polymer2.html` file
2. When visiting this compiled file in a ES6-ready browser (e.g. Chrome 58), a header with the content `polymer2-app` should appear

#### Actual Results

1. None of that happens
2. Blank page with the following errors in console : `Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

#### Additional information

If I manually add `<script src="/bower_components/webcomponentsjs/custom-elements-es5-adapter.js"></script>` in the index file `/demo/polymer2.html`, the compiled ES5 code works but `polymer serve` displays a blank page with the following error in console for every custom element used : `Uncaught TypeError: Class constructor DomModule cannot be invoked without 'new'`.

**Comment by adamdoyle** [comment]
Might be useful to add something to the adapter section of the readme to warn that it must come before `bundler()`.  I just ran into this myself and it took me awhile to figure it out.
