### ISSUE TITLE
$npm install -g polymer-cli   gives EACCES: permission denied, mkdir

### ISSUE THREAD

**Issue by JoeCodeswell** [Polymer/tools#2498]
### Description
I am trying to install polymer-cli 2
$ install -g polymer-cli   
    gives EACCES: permission denied, mkdir

### Versions & Environment
I am running Bash on Ubuntu On Windows (10) "As Administrator"/root

joebash@joethinks:~$ sudo su root
[sudo] password for joebash:

root@joethinks:/home/joebash# node --version
v7.10.1

root@joethinks:/home/joebash# git --version
git version 1.9.1

#### Steps to Reproduce
root@joethinks:/home/joebash# git --version
root@joethinks:/home/joebash# npm install -g bower
root@joethinks:/home/joebash# npm install -g polymer-cli

#### Expected Results
No error is thrown 

#### Actual Results

    root@joethinks:/home/joebash# git --version
    git version 1.9.1

    root@joethinks:/home/joebash# npm install -g bower
    npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is se
    curity and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it
    : https://github.com/bower/bower/issues/2467
    /usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
    + bower@1.8.0
    updated 1 package in 36.689s

    root@joethinks:/home/joebash# npm install -g polymer-cli
    npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is se
    curity and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us fi
    gure out one.
    npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
    /usr/bin/polymer -> /usr/lib/node_modules/polymer-cli/bin/polymer.js

    > wd@1.4.0 install /usr/lib/node_modules/polymer-cli/node_modules/wd
    > node scripts/build-browser-scripts

    /usr/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
                        throw err0;
                        ^

    Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/wd/build'
        at Object.fs.mkdirSync (fs.js:895:18)
        at sync (/usr/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
        at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:427:7)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! wd@1.4.0 install: `node scripts/build-browser-scripts`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the wd@1.4.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2017-07-29T18_03_53_599Z-debug.log
    root@joethinks:/home/joebash#

[debug-log.txt](https://github.com/Polymer/polymer-cli/files/1187978/debug-log.txt)

**Comment by npsedhain** [comment]
Thanks @guss77 , i was stuck there too! thanks for pointing out !
