### ISSUE TITLE
v1.5.1, peer dependency "sinon" is missing

### ISSUE THREAD

**Issue by thomasweitzel** [Polymer/tools#2508]
### Description

Update to version 1.5.1 leads to error `npm ERR! peer dep missing: sinon@^1.4.0 || ^2.1.0 || ^3.0.0, required by sinon-chai@2.13.0` (`npm WARN sinon-chai@2.13.0 requires a peer of sinon@^1.4.0 || ^2.1.0 || ^3.0.0 but none was installed.` is shown during update).

### Versions & Environment

- Polymer CLI: 1.5.1
- node: 6.11.2
- Operating System: Ubuntu 14.04 (4.4.0-92-generic)

#### Steps to Reproduce

1. Update from previous version with `npm -g update`
2. List installed packages with `npm -g list --depth=0`

#### Expected Results

```
/home/test/.npm-global/lib
├── bower@1.8.0
├── npm@5.3.0
└── polymer-cli@1.5.1
```

#### Actual Results

```
/home/test/.npm-global/lib
├── bower@1.8.0
├── npm@5.3.0
└── polymer-cli@1.5.1

npm ERR! peer dep missing: sinon@^1.4.0 || ^2.1.0 || ^3.0.0, required by sinon-chai@2.13.0
```
#### Manual fix
Install missing dependency with `npm -g install sinon`.

**Comment by salamanders** [comment]
Hello from the future!  Strange that this still pops up:
```
$ npm list -g --depth=0
/Users/ME/brew/homebrew/lib
├── bower@1.8.8
├── cordova@8.1.2
├── firebase-tools@6.3.1
├── gulp@4.0.0
├── npm@6.7.0
└── polymer-cli@1.9.6

npm ERR! peer dep missing: sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0, required by sinon-chai@2.14.0
npm ERR! peer dep missing: chai@>=1.9.2 <5, required by sinon-chai@2.14.0
```

**Comment by jackeymason** [comment]
Tried the manual fix but getting the same issue when trying to install polymer dependencies.
