### ISSUE TITLE
Tagged template literals incorrectly transpiled to es5

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/tools#2570]
Tagged template literals are transpiled incorrectly to es5. _templateObject variables are placed outside script closures and end up on the global scope. This causes multiple tagged template literals to override each other. 

I've investigated this, and it seems that babel is expecting to be in a module scope rather than a global scope. I am not sure if this is due to how babel is configured inside the polymer cli, or a bug within the babel transformer.

The same transpilation done by the typescript compiler provides valid output, it does not place variables outside closures.

This affects polyserve as well as polymer build. It happens on .js and .html files.

A minimal reproduction is like this:

Given two files:

html-file-a.html
```
<link rel="import" href="../bower_components/polymer/lib/utils/html-tag.html">
<link rel="import" href="./html-file-b.html">

<script>
  (function () {
    const a = window.Polymer.html`<div>A</div>`;
  })();
</script>
```

html-file-b.html
```
<script>
  (function () {
    const b = window.Polymer.html`<div>B</div>`;
  })();
</script>
```

And the following polymer.json:
```
{
  "entrypoint": "index.html",
  "shell": "src/html-file-a.html",
  "fragments": [
  ],
  "sources": [
    "src/**/*"
  ],
  "extraDependencies": [
    "bower_components/webcomponentsjs/*"
  ],
  "builds": [
    {
      "preset": "es5-bundled"
    }
  ]
}
```

Produces the following output:
```
<html><head></head>
<body>
  <div hidden="" by-polymer-bundler="">
    <script>... insertions by polymer omitted for brevity...</script>
    <script>var _templateObject = babelHelpers.taggedTemplateLiteral(["<div>B</div>"], ["<div>B</div>"]); (function () { window.Polymer.html(_templateObject) })();</script>
    <script>var _templateObject = babelHelpers.taggedTemplateLiteral(["<div>A</div>"], ["<div>A</div>"]); (function () { window.Polymer.html(_templateObject) })();</script>
  </div>
</body>
</html>
```

Versions:
Polymer CLI v1.5.7
Polymer Build v2.1.1
Polymer Bundler v3.1.1

**Comment by livevsonline** [comment]
I am having major problems with a tagged string literal templater function which uses string manipulation... i had to convert a websites javascript into a webpack compitable structure with imports/exports on a multi page website.

And ive now spend over 72hours of my own time, trying to figure out what the hell is going on.

Apparently webpack bundles tagged templates wrong. if you have a tagged template function and you call it from within an object etc {test: templater`my template function ${'manipulation'}` and then call the test() from a packed webpack module... it wount recognize it as a function.
