### ISSUE TITLE
Unable to run build application on IE11

### ISSUE THREAD

**Issue by motss** [Polymer/tools#2603]
### Versions & Environment

- Polymer CLI: 1.7.2
- node: 8
- Operating System: Windows 10 x64

#### Steps to Reproduce

1. Create an application project: `polymer init` -> Choose `polymer-3-starter-kit`
2. Build: `polymer build`.
3. Open IE 11, shows me `Unable to get property 'src' of undefined or null reference` which leads me to this section of code:

```js
 if (polyfills.length) {
        var script = document.querySelector("script[src*=\"" + name + "\"]"), newScript = document.createElement("script"), replacement = "bundles/webcomponents-" + polyfills.join("-") + ".js", url = script.src.replace(name, replacement);
        newScript.src = url;
        if ("loading" === document.readyState) {
            newScript.setAttribute("onload", "window.WebComponents._batchCustomElements()");
            document.write(newScript.outerHTML);
            document.addEventListener("DOMContentLoaded", ready);
        }
```

#### Expected Results

Runs application without issue on all supported browsers.

#### Actual Results

Everything works with just `polymer serve`. Break on IE11 after `polymer build`.

**Comment by jdvivar** [comment]
The solution for me was to use ```webcomponents-lite.js``` instead of ```webcomponents-loader.js```, I hope it helps.
