### ISSUE TITLE
clearing empty build folder takes up to 30 seconds

### ISSUE THREAD

**Issue by sebs** [Polymer/tools#2615]
### Description

polymer build reserves about 20 secs time to 

"info: [cli.command.build]    Clearing build/ directory..."

Although I ran 

```
rm -rf build && mkdir build && polymer build
```

Kinda odd, that 30 seconds are reserved, probably waiting for a timeout. Especially when building löarge collections of Components.

### Versions & Environment

- Polymer CLI: latest
- node: 9.11.2
- Operating System: Ubuntu

#### Steps to Reproduce
1. Create an application project: `polymer init application`
2. if in filesystem: delete build folder
3. Build: `polymer build`

-->

#### Expected Results
The "remove build step" completes asap. 

#### Actual Results
The step uses up top 30 seconds, even when there is no build folder to delete

**Comment by tjanson** [comment]
Hey @sebs, did you close this issue because you figured out a solution? I’m encountering the same thing.

**Comment by sebs** [comment]
@tjanson no, and yes its in fact much longer.

**Comment by sebs** [comment]
Abandon as much as you can from the polymer build stack. The dev team has done some lifting beyond  its capabilities.  There is a web components initiative, this is what I am banking on - its providing test tools - not self written, but others configured for polymer. As much as I am concerned: most of the tools here only half assed replace some tools that are there out in the open. And polymers release and fix cycles do not really match professional project lifecycles.  

Plus: they do vendor lock in with the build chain ... just as an experiment ... try to fork and release stuff from the tools repos, you will see .. google makes it very hard. 

The polymer project is basically a organized form of Google to pick up IP (intellectual property) from devs to re sell it as its own (hence the CLA bot) so apart from getting speakers on conferences and influencing the W3c standards process ( which did not wirk, hence the import refactoring) they do not seem to want a ready made product built and are not very supportive. 

Same goes for their implementation of material components. Sometimes the projects feels like an organized approach from google to hinder the development of new frameworks and technologies, until Google has figured out. You know what, truth has to be told: If there was one proof, that "Googlers" are living human being, as mediocre as the rest of us. Only they are allowed to sell off code that goes under the CLA as their own. 

Look at the polymer chat, if it was not for one or the other person from vaadin, the whole thing would be just dead. 

And NO; I do not want to sign a CLA, I do not want anything .. I want the stuff in the shape that google promised it .... professionally developed and NOT waiting 3-54 Months until bugs and PRS get answered.

**Comment by web-padawan** [comment]
> if it was not for one or the other person from vaadin, the whole thing would be just dead.

Thanks for the mention, but I would like to highlight that there are some open source enthusiasts in the community now, who work on the [open-wc.org](https://open-wc.org) project, collecting the best practices and recommendations for testing and building web components. You can reach them out into [#open-wc](https://polymer.slack.com/messages/CE6D9DN05) channel in Polymer Slack.

I agree that using mainstream tools like webpack and Karma makes more sense now. For a long time, Polymer community has been staying aside because of Bower and HTML imports, now it is in our hands to drive the progress for elaborating better workflow.

**Comment by sebs** [comment]
I was mentioning open-wc, but skip the name ;) Thanks. Sorry for being so publicly angry and surely rude, but a look in the bugtracker of /tools or the many material elements should make my pooint clear. It does not lack user contribution in the polymer world, google has just a very hard time integrating user needs in its own agenda.

**Comment by tjanson** [comment]
I’ve also encountered it effectively hanging now (5+ min). I don’t have further info about that for debugging purposes (I just killed the process, maybe I’ll take a closer look next time).

But in any case, maybe you could reopen the issue since it is not resolved, @sebs. Thanks. (Feel free to unsubscribe ;) .)

**Comment by sebs** [comment]
Hey, I can not open this again, but I think I opened it in tool back then as well.

**Comment by tjanson** [comment]
@sebs I see, thanks.

@aomarks @rictic Feel free to reopen. This is unresolved.

**Comment by tjanson** [comment]
The deletion of the build directory actually doesn’t take long at all – that just happens to be the last message.
When running with `--verbose`, it’s clear that the long wait is during or after analysis of the node dependencies. That seems more reasonable (the dependency tree is huge).

So this may not be a “real” issue at all, other than an unfortunate user experience.

**Comment by sebs** [comment]
ah, thats neat, and logical. do we open a issue to drop us a log message once the next process starts? This would maybe cover other cases as well.
