### ISSUE TITLE
[all] Reduce test run times

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/tools#269]
This is a meta bug to brainstorm and track ideas to reduce the total test run time, both on CI and locally.

- Use yarn workspaces, which might be faster than Lerna installing each external dependency one at a time.
- Manually hoist dev dependencies like typescript, tslint, gulp, etc., to the top-level package.json
- Use `lerna bootstrap --hoist`
- Use `npm ci`, which is supposedly 2-3x faster than `npm i`. We need to see if `lerna bootstrap` can use that command. This might be mutually exclusive with yarn workspaces.
- Reduce the number of browsers we run certain integration tests on, especially for tests that check server-side setups and don't vary across browsers.
- Reduce startup times in general - trim or lazy load dependencies, eliminate large ones like selenium-standalone, etc.

**Comment by merlinnot** [comment]
I see that `lerna bootstrap` takes > 80 sec. I've gone through the CI configuration and I can't find any caches. If we add packages to the cache, this step should then take no more than a few seconds.

I generally like yarn workspaces, but these should be cached too.
