### ISSUE TITLE
[lint] Internal error during linting: Cannot read property '__location' of undefined

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#272]
### Description
After upgrading to latest polymer-cli, we get the internal lint error when linting `vaadin-text-field`.

```sh
$ polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html

<!--
~

src/vaadin-text-field.html(1,1) warning [internal-lint-error] - Internal error during linting: Cannot read property '__location' of undefined

Found 1 warning.
```

### Versions & Environment
- polymer-cli: 1.7.0-pre.15
- node: 8.11.1
- Operating System: Mac OS

#### Steps to Reproduce

1. Clone the repo:
```sh
git clone https://github.com/vaadin/vaadin-text-field && cd vaadin-text-field
```

2. Install the CLI:
```sh
npm i g polymer-cli@next
```

3. Install bower dependencies:
```sh
bower i
```

4. Run the lint:
```sh
polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html
```

### Expected result

No errors or warnings, as with CLI 1.6.0

### Actual result

The internal error described above. See also [Travis build](https://travis-ci.org/vaadin/vaadin-text-field/jobs/373009779).

Interestingly, so far it only affects one repo though. It seems to be an analyzer issue, but I'm not really sure at which point was it introduced. Have also tried earlier preview versions with the same result.

**Comment by web-padawan** [comment]
@rictic FYI, now when the CLI is stable, some builds might fail because of this issue. 
We had to disable it in vaadin/vaadin-text-field@442e954

**Comment by davidmaxwaterman** [comment]
I also see this error, output for every file since the first line of every file is an html comment ```<!-- %TBCVERSION% -->``` (replaced at build time)

**Comment by web-padawan** [comment]
The reason found and described in #408, closing in favor of that one.
