### ISSUE TITLE
polymer test: module is not define

### ISSUE THREAD

**Issue by abdonrd** [Polymer/tools#2807]
When I test the modulizered elements I get this error:

<img width="467" alt="screen shot 2018-05-12 at 20 10 16" src="https://user-images.githubusercontent.com/1007051/39960297-89d328e2-5620-11e8-87a5-174555b1405d.png">

And I don't use lodash... I supose is something from the modulizer and/or the WCT.

**Comment by jarrodek** [comment]
I run into the same problem today after running the modulizer on mu components

**Comment by abdonrd** [comment]
Closing and old issue.
