### ISSUE TITLE
Does the latest version of WCT work with bare import specifiers?

### ISSUE THREAD

**Issue by lastmjs** [Polymer/tools#284]
Just wondering if WCT supports the new bare import specifiers, I'm using web-component-tester@6.6.0-pre.5

**Comment by TimvdLippe** [comment]
The prerelease has support via `--module-resolution`: https://github.com/Polymer/tools/blob/master/packages/web-component-tester/CHANGELOG.md#660-pre3---2018-03-21

**Comment by aomarks** [comment]
If you install `@next` and run with `--npm --module-resolution=node` then bare specifiers should be rewritten to paths.

**Comment by lastmjs** [comment]
So: `wct --npm --module-resolution=node`?

**Comment by aomarks** [comment]
> So: wct --npm --module-resolution=node?

Yes. You can also set "npm:true" and "moduleResolution:node" in your wct.conf.json

**Comment by lastmjs** [comment]
Sorry, I'm getting this error: `Error: wct-browser-legacy not installed. Please change --wct-package-name flag or install the package.` Do I just need to do an npm install of `wct-browser-legacy`? Is there documentation for any of this yet?
