### ISSUE TITLE
Not starting tests in IE11 and 404 errors in the network tab

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#293]
### Description
After upgrading to latest polymer-cli 1.7.0-pre.16 released today, we get the 404 requests when running tests in IE11, and the tests are not starting at all.

Those 404 errors also appear in Edge but apparently not affecting tests. So there might be 2 problems here, actually. Also noticed that request URLs ending up with 404 errors in Edge look differently:

- IE11: http://10.0.2.2:8081/components/@vaadin/vaadin-themable-mixin/test/undefined
- Edge: http://10.0.2.2:8081/components/@webcomponents/webcomponentsjs/%20[synthetic:util/global]

The issue is most likely caused by the new loader, assuming that was the only significant change since the pre.15 release of the CLI, which works in IE11 when serving the same code base.

I do not see such errors in the latest Firefox, though. And the requests in Edge seem related to the Babel stuff, so it might be that the problem is there.

### Versions & Environment
- polymer-cli: 1.7.0-pre.16
- node: 8.11.1
- Operating System: Mac OS

#### Steps to Reproduce

1. Clone the repo:
```sh
git clone --depth 1 -b p3-preview-next git://github.com/vaadin/vaadin-themable-mixin.git && cd vaadin-themable-mixin
```

2. Install the modulizer:
```sh
git clone --depth 1 -b polyfill-v2 git://github.com/web-padawan/polymer-modulizer.git && cd polymer-modulizer && npm link
```

3. Install the tools:
```sh
npm i -g bower yarn magi-cli polymer-cli@next
```

4. Install bower dependencies:
```sh
bower install
```

5. Run the conversion:
```sh
magi p3-convert --out . --import-style=name
```

6. Install dependencies:
```sh
yarn installl --flat
```

7. Serve the component:
```sh
polymer serve --npm --module-resolution=node
``` 

8. Open IE11 and go to http://127.0.0.1:8081/components/@vaadin/vaadin-themable-mixin/test/

### Expected Results (polymer-cli 1.7.0-pre.15)

Tests are passing, no 404 errors in the network tab: 

![screen shot 2018-05-02 at 11 12 48](https://user-images.githubusercontent.com/10589913/39512918-3e252b84-4dfb-11e8-9c24-57c9e04f94a4.png)

### Actual Results (polymer-cli 1.7.0-pre.16)

Tests not starting, the 404 errors in the network tab:

![screen shot 2018-05-02 at 11 10 34](https://user-images.githubusercontent.com/10589913/39512923-42b985be-4dfb-11e8-9ebe-9b357cf9b68e.png)

Errors in Edge (different number - 6 errors, also different request URLs): 
![screen shot 2018-05-02 at 11 25 10](https://user-images.githubusercontent.com/10589913/39513061-b32517fa-4dfb-11e8-8600-4cfbe8b47808.png)

**Comment by aomarks** [comment]
Did the modulizer version change at all between before the regression above and now?

**Comment by web-padawan** [comment]
I'm only able to reproduce the issue with the latest modulizer Polymer/polymer-modulizer#413
When running the older one, referencing polyfill v1 and the polymer 3.0.0-pre.12, the error does not appear.

But the output of the latest modulizer still works with the CLI 1.7.0-pre.15 so it seems that indeed there are actually 2 problems here, and one is either on the polyfill v2 or modulizer side.

**Comment by aomarks** [comment]
I was able to reproduce this in a VM, although I still don't have much of an idea what's going on. I don't think it's related to the AMD loader -- the 404ing URLs seem to be things from webcomponentsjs, which makes me think it's probably an issue with the new webcomponentsjs loader. I see that 2.0.0-beta.2 is installed, which is the latest version.

@kevinpschaaf FYI

**Comment by web-padawan** [comment]
That makes sense, but please also consider the fact that tests are passing in IE11 with the earlier version of the CLI, as mentioned in the issue.

Se e. g. vaadin/vaadin-checkbox@bd0dffb and the [Travis job](https://travis-ci.org/vaadin/vaadin-checkbox/jobs/373927651) for it.

**Comment by web-padawan** [comment]
Thanks for the fix! I have tried it and it worked locally, will update our CI builds to ensure the tests pass.

**Comment by kevinpschaaf** [comment]
Confirmed fixed the issue in polymer tests.
