### ISSUE TITLE
[bundler] Generate the __bundleImportMeta variable name to ensure it does not conflict

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#310]
In bundling es6 modules, we inject a variable in the bundled module when it references `import.meta` somewhere in the code, and this is currently statically named `__bundledImportMeta`.  However, we need a way to ensure this name doesn't conflict before injecting it.  To do that, we should run a test on the source to see if that value exists somewhere and if so we can increment a number suffix on it or something to ensure uniqueness.

**Comment by aomarks** [comment]
Example of how to do this here:https://github.com/Polymer/tools/blob/master/packages/build/src/babel-plugin-import-meta.ts#L58

**Comment by usergenic** [comment]
I fixed this in #344 but I missed seeing your comment linking to use of the built-in id-generator in `path.scope`.  Derp.
