### ISSUE TITLE
SyntaxError: redeclaration of const $_documentContainer on Firefox

### ISSUE THREAD

**Issue by e111077** [Polymer/tools#315]
repro case:

```js
// a.js
const foo = 'bar';

// b.js
const foo = 'baz';
```

```html
// index.html
<script type="module">
  import './a.js';
  import './b.js';
</script>
```

This will cause a `SyntaxError: redeclaration of const foo` on Firefox. I assume this may happen to other transformed browsers

**Comment by aomarks** [comment]
Whats the build configuration?

**Comment by e111077** [comment]
`polymer serve --npm --module-resolution node`

**Comment by e111077** [comment]
also happens on `polymer test` with the same flags

**Comment by web-padawan** [comment]
@aomarks FYI, one of our users has faced the similar issue: vaadin/vaadin-grid#1379
Any chance to someone from the Tools team to look at this?
