### ISSUE TITLE
Changing default timeout duration

### ISSUE THREAD

**Issue by dulimarta** [Polymer/tools#3196]
I was not able to find a clear documentation for changing the timeout duration when running my test cases under wct. I tried several places for setting `testTimeout` in `wct.conf.js` but none of them seems to work. 

    module.exports = {
      testTimeout: 20000,
      plugins: {
        local: {
          testTimeout: 20000,
          browser: ['chrome']
        }
      },
      clientOptions: {
        mochaOptions: {
          timeout: 20000
        }
      }
    }

Regardless of other keys I tried (`idleTimeout`, `timeout`), the timeout duration is always 10000 ms and the error on my browser window is

     Error: Timeout of 10000ms exceeded. For async test and hooks, ....

**Comment by motss** [comment]
According to this line at https://github.com/Polymer/tools/blob/master/packages/web-component-tester/runner/config.ts#L166, the default `testTimeout` is `90e3` ms. By increasing this field, I no longer seeing unknown timeout from WCT.

**wct.conf.json**

```json
{
  "moduleResolution": "node",
  "npm": true,
  "plugins": {
    "local": {
      "browsers": [
        "chrome"
      ],
      "browserOptions": {
        "chrome": [
          "disable-gpu",
          "headless",
          "window-size=1920,1080"
        ]
      }
    }
  },
  "testTimeout": 600000,
  "suites": ["src/test"],
  "verbose": true
}
```
