### ISSUE TITLE
lodash: module is not defined

### ISSUE THREAD

**Issue by NeoLegends** [Polymer/tools#3237]
Hey!

I'm using web-component-tester just with a JS file. When testing I always get errors during test initialization.

![image](https://user-images.githubusercontent.com/1683034/35098780-cca5d252-fc55-11e7-981f-c214aad3a926.png)

Seems like something wrong with transpilation / index.js selection? Funnily enough, my actual tests still run. Its just that the end result never terminates with OK because that one thing fails.

**Comment by soccercrazy** [comment]
Hi @aomarks,

This issue is still happening for me using:

`"wct-browser-legacy": "^1.0.2"`

whenever another package depends on lodash >= 4.  Should it not be "**Closed**" or is there another branch I should be using instead?

Thanks!
