### ISSUE TITLE
Testing 'fetch'?

### ISSUE THREAD

**Issue by leegee** [Polymer/tools#3343]
The general recommendation seems to be 'use WCT for testing' but on trying to use the popular `fetch-mock`, the dread `require is not defined`. 

How to mock HTTP calls made via `fetch`?

Will I just have to `<script src="/node_modules/fetch-mock/dist/es5/client-bundle.js"></script>`?

**Comment by kylebuch8** [comment]
You can use `sinon.stub(window, "fetch");`

This test has an example of how I mocked a fetch call. Just make sure you call `window.fetch.restore();` when you're done.

https://github.com/patternfly/patternfly-elements/blob/more-like-this/elements/cp-more-like-this/test/cp-more-like-this_test.html#L24

And here's another gist.
https://gist.github.com/coder36/a5c6f37623a066e50bbe52dd258b77f0

**Comment by leegee** [comment]
Just in case it helps anyone else — `fetch-mock` comes with a `dist`
directory.

Sorry I wasn't clear — I wanted to know if the framework supported an API
call.

>
