### ISSUE TITLE
Webpack?

### ISSUE THREAD

**Issue by leegee** [Polymer/tools#3344]
I'vegot a custom Webpack build that allows me to have templates in plain HTML, *css in native form — but obv WCT doesn't like that. Is there any way to run WCT against compiled code?

**Comment by web-padawan** [comment]
Consider using `karma-webpack` if you wish to use webpack loaders in development.
See for example https://open-wc.org/testing/testing-karma.html#browser-testing

**Comment by leegee** [comment]
Many thanks — great to learn of WC-Open, though silly name (WC in Europe means Water Closet, which is a toilet). 

Not quite working and I have 7 days to write the tests, so I'll adjust the code to work with WCT.

https://github.com/open-wc/open-wc/issues/175

**Comment by web-padawan** [comment]
If you are looking for a ready config example using Karma, you can also check my repo:
https://github.com/web-padawan/lit-components/blob/master/karma.conf.js

I am not using any custom loaders, though (it does not make sense in my project).
