### ISSUE TITLE
When loading via AMD loader, module execution order can be unexpected

### ISSUE THREAD

**Issue by sorvell** [Polymer/tools#335]
This causes flakiness in ShadyCSS style processing because that library has load order requirements that users must adhere to.

1. a test loads [polymer-legacy.js](https://github.com/Polymer/polymer/blob/3.x-test-green/test/unit/styling-only-with-template.html#L18)
2. polymer-legacy loads
   * [legacy-element-mixin](https://github.com/Polymer/polymer/blob/3.x-test-green/polymer-legacy.js#L11)
     * legacy-element-mixin loads [apply-shim as its first import](https://github.com/Polymer/polymer/blob/3.x-test-green/lib/legacy/legacy-element-mixin.js#L10)
   * [custom-style](https://github.com/Polymer/polymer/blob/3.x-test-green/polymer-legacy.js#L20)

Based on this, I expect `apply-shim` to load and execute before `custom-style`.

However, it does not (verified via logging and Edge element inspector):

![screen shot 2018-05-04 at 7 33 29 pm](https://user-images.githubusercontent.com/78891/39658979-66a6ba80-4fd3-11e8-9a0c-ead3352d75bc.png)

**Comment by rictic** [comment]
I think what's happening is that we're not following the full es6 import ordering semantics. If you've got:

#### start.js
```js
import 'foo';
import 'baz';
```

#### foo.js
```js
import 'bar';
```


Then the execution order is defined as: `bar, foo, baz, start`, but I think our loader is racy and might run baz _first_. 

So to do this right we can't just run module bodies when all of their imports are present, we also need to obey ordering of their parents' dependencies, which can be extra tricky when cycles get involved.

I'll put together some tests to verify that this is what's happening.
