### ISSUE TITLE
Polymer CLI: Could you please support commonJS ?

### ISSUE THREAD

**Issue by alexandru-tomescu** [Polymer/tools#3365]
Hi. We are building a new project using Polymer CLI and Lit element and we want to try https://github.com/amcharts/amcharts4 but we have some issues in development time: we cannot use es6 modules provided by them. I opened a issue (https://github.com/amcharts/amcharts4/issues/977) to their repo, and they said this is a Polymer responsibility to provide CommonJS modules support. What do you think about this ? Thank you.

**Comment by web-padawan** [comment]
This has been discussed many times, and the position of Polymer team was that they only support ES modules intentionally, as CommonJS is node-specific. Consider using other tools like webpack or rollup if you need to use CommonJS dependencies in your project.

**Comment by alexandru-tomescu** [comment]
Oh... i understand. Thank you, @web-padawan !
