### ISSUE TITLE
Incorrect reference: polymer-project-config

### ISSUE THREAD

**Issue by anoblet** [Polymer/tools#3373]
It looks as if the polymer-project-config package was renamed to project-config though a few modules have not been updated.

https://github.com/Polymer/tools/search?q=polymer-project-config&unscoped_q=polymer-project-config

**Comment by web-padawan** [comment]
Only the folder has been renamed, same happened to most of packages. Basically, the `polymer-` prefix was removed for folder names: analyzer, build, bundler, cli, editor-service, linter, modulizer.
