### ISSUE TITLE
[wct-mocha] Doesn't work with the latest major version of mocha (^6.0.0)

### ISSUE THREAD

**Issue by svanherk** [Polymer/tools#3394]
### Description

When using `wct-mocha` with `mocha` version `^6.0.0`, the tests start to run but then the following error is thrown at https://github.com/mochajs/mocha/blob/master/lib/reporters/html.js#L236:
```
TypeError: Cannot read property 'tests' of undefined
```

I believe this is happening because of the following [breaking change in version 6](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes):
```
#3458: Instantiating a Base-extending reporter without a Runner parameter will throw an exception
```
As part of this, statistics were refactored out into their own helper: https://github.com/mochajs/mocha/pull/3458/files

If I pull [`lib/stats-collector.js`](https://github.com/mochajs/mocha/pull/3458/files#diff-9a6795534cc0c3713fbaa297302a0566) into `wct-mocha`, and then add `createStatsCollector(runner);` before these two lines, the tests appear to start working again:
https://github.com/Polymer/tools/blob/master/packages/wct-mocha/src/reporters/console.ts#L84
https://github.com/Polymer/tools/blob/master/packages/wct-mocha/src/reporters/title.ts#L24

### Versions

- `wct-mocha ^1.0.0`
- `mocha ^6.0.0` (`mocha ^5.0.0` is fine)

**Comment by simondel** [comment]
@rictic @usergenic @azakus @justinfagnani @aomarks @FredKSchott Would it be possible to get an update on this?
