### ISSUE TITLE
Multiple Builds memory issue

### ISSUE THREAD

**Issue by homerjonathan** [Polymer/tools#3400]
My project is getting quite large and I have 3 builds say, production, development and localtest.  If I use **polymer build** the build fails with memory heap error.  However if I run 

```
polymer build --name production
polymer build --name development
polymer build --name localtest
```

It works perfectly.  When running effectively 3 builds at the same time it can exhaust the memory. I had expected the CLI to run build for each version behind the scenes and not require much more memory. I have also found that running the build command separately for each build required is quicker despite running it 3 times instead of once.

**Comment by jsilvermist** [comment]
Please note that you are naming a default build (no compiling or minifying) and not selecting builds from `polymer.json` when you use `--name` in this way.

**Comment by rbjarnason** [comment]
This works for me, adjust the memory size as needed:
NODE_OPTIONS="--max-old-space-size=2072" polymer build

**Comment by homerjonathan** [comment]
You are correct when building with the --name I thought it would "look up" the build instructions, however it doesn't. I have ran polymer build with just one item in the builds list and it then builds correctly.  It may be worth adding an option similar to --name to choose which build you want to save memory.

Thanks for the suggestion this works with one item.  It also completes the build process a bit faster as well.  However with the three builds it fails to build.

It seems that my only option is to use the --name option but add the build options as a work around.
