### ISSUE TITLE
custom build - build multiple projects with only one node_modules

### ISSUE THREAD

**Issue by QuinsZouls** [Polymer/tools#3418]
# I have multiple proyects of polymer, but each one has its own modules to be compiled
![2019-05-18_10-21-34](https://user-images.githubusercontent.com/40646096/57971756-b8241980-7957-11e9-94c7-e7b98dfe737c.png)
![2019-05-18_10-22-09](https://user-images.githubusercontent.com/40646096/57971692-d5a4b380-7956-11e9-9c93-586c4bdedaf0.png)
## Using custom build tools for build pwa
```javascript
const fs = require('fs-extra');
const polymerBuild = require('polymer-build');
const path = require('path');
const build = require('./build/build').build; // custom polymer builder
const utils = require('./util');

/**
 * @param {String} name 
 */
async function buildProyect(name) {
  var setting = require(path.join(
    __dirname,
    '..',
    'proyects',
    name,
    'polymer.json'
  ));
  setting.root = path.join(__dirname, '..', 'proyects', name); //configure path root of the proyect

  const project = new polymerBuild.PolymerProject(setting);
  const buildSettings = utils.getBuildSettings(name);
  let arr = [];
  for (setting of buildSettings) {
    arr.push(build(setting, project, name));
  }
  await Promise.all(arr);
}
```
### My idea is to put the node_modules in the project folder, but when doing this the constructor always looks in the root of the project, now my question is: How do I take the node_modules of the project directory to build the pwa?
![2019-05-18_13-31-48](https://user-images.githubusercontent.com/40646096/57973645-b6674f80-7971-11e9-95d0-add0fca1b9e5.png)
### for that I tried to put the absolute path where the modules were in the file polymer.json, but it did not work
![2019-05-18_13-37-28](https://user-images.githubusercontent.com/40646096/57973680-6341cc80-7972-11e9-84ea-23e7cc838b4e.png)

**Comment by jsilvermist** [comment]
What about using symlinks?

**Comment by QuinsZouls** [comment]
i am used [build script](https://github.com/Polymer/tools/blob/master/packages/cli/src/build/build.ts)  but apparently the script does not take up symlinks

**Comment by QuinsZouls** [comment]
This is my implementation but I'm not sure if it's adequate
```javascript
const symlinkDir = require('symlink-dir');
const path = require('path');

const modules = path.join(__dirname, '..', 'proyects', 'node_modules');

/**
 *
 * @param {String} utl path of node_modules 
 */
function createNodeLink(utl) {
  return symlinkDir(modules, utl)
    .then(result => {
      console.log(result);
      return symlinkDir(modules, utl);
    })
    .then(result => {
      console.log(result);
    })
    .catch(err => console.error(err));
}
module.exports = {
  createNodeLink
}
```
