### ISSUE TITLE
looking for wct-browser-legacy@1.0.2

### ISSUE THREAD

**Issue by txm** [Polymer/tools#3459]
Anyone know where I can find the source for wct-browser-legacy@1.0.2? TIA

**Comment by usergenic** [comment]
Technically it's at this tag in this folder.

https://github.com/Polymer/tools/tree/wct-browser-legacy%401.0.2/packages/wct-browser-legacy

**Comment by usergenic** [comment]
Sorry LOL source of that version should be in web-component-tester at https://github.com/Polymer/tools/tree/wct-browser-legacy%401.0.2/packages/web-component-tester
