### ISSUE TITLE
`polymer build` bundling for web workers

### ISSUE THREAD

**Issue by PixlRainbow** [Polymer/tools#3472]
How do I configure `polymer.json` to bundle dependencies listed in `importScripts` in a custom web worker (NOT service worker) javascript file?
I notice that even without configuration, `polymer build` automatically minified my worker script file and copied it to the built folder, where the built application would stop working because the web worker was unable to find scripts it needed to import.

**Comment by Raizuuuuu** [comment]
help

**Comment by PixlRainbow** [comment]
worked around by adding additional build step with webpack. Am no longer a maintainer for the affected project as of February 2020.
