### ISSUE TITLE
error [parse-error] - Unexpected token ...

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/tools#356]
Ref: https://github.com/Polymer/polymer-analyzer/issues/846

I'm using Polymer v1 and a gulpfile using polymer-build@1.6.0 and polymer-analyzer@2.7.0.

Can someone tell me how I can get the fix?

**Comment by davidmaxwaterman** [comment]
FWIW, I managed to get things working by changing, in my package.json:

 ```
   "polymer-build": "^1.0.0",
```
to
```
   "polymer-build": "^3.0.0",
```

and commenting out:

```
          .pipe(gulpIf(/\.js$/, gulpBabel({presets: ['es2015']})))
```

I guess I lost some compatibility with older browsers, but I can accept that (famous last words).

**Comment by rictic** [comment]
Can you post your full polymer.json?

**Comment by davidmaxwaterman** [comment]
Some stuff snipped, but hopefully it has the info you ask for (npm ls output is quite long):

[polymer_json.txt](https://github.com/Polymer/tools/files/1992523/polymer_json.txt)
[npm_ls.txt](https://github.com/Polymer/tools/files/1992524/npm_ls.txt)
