### ISSUE TITLE
Failed to resolve module specifier

### ISSUE THREAD

**Issue by jimmont** [Polymer/tools#363]
**what parameters** does `polymer build` use as input to determine **_what import paths to fix_** (so they work client-side with `import { something } from './my/current/reality`)?

after building with polymer build, when I run my project (the server is not related to polymer at all, and should not be either) a `node_modules` import path that is not `@polymer` (it's `@vaadin`) fails to translate:
`Uncaught TypeError: Failed to resolve module specifier "@polymer/polymer/lib/utils/import-href.js". Relative references must start with either "/", "./", or "../".`

What problem are named imports attempting to solve? (Since this problem stops my entire effort and has no obvious benefit to me.)

**Comment by web-padawan** [comment]
FYI, the error was related to the not existing import and the hotfix for Vaadin component has been already published.

My point here is that error text was misleading: import is using bare module specifier, but the export not exists. It should look domething like "there is no export called importHref in module" etc.

**Comment by jimmont** [comment]
Thanks @web-padawan should this be closed as a result? Or does it indicate any sort of meaningful issue to track? If not I or anyone can go ahead and close it.

**Comment by jimmont** [comment]
Thanks @web-padawan, based on your feedback this doesn't appear to be relevant to polymer tools in a significant enough way to keep the issue open.
