### ISSUE TITLE
There are any plans to reduce the Polymer CLI size?

### ISSUE THREAD

**Issue by abdonrd** [Polymer/tools#372]
Right now the Polymer CLI is a little big.

<img width="806" alt="screen shot 2018-05-12 at 23 21 03" src="https://user-images.githubusercontent.com/1007051/39961648-29829a98-563b-11e8-9ab9-22080c295496.png">

In my computer:
* Time to install: 37.15s
* Size: 285M

Now with the next-generation tools like lit-html, LitElement, PWA Starket Kit, etc

When I talk to people about PWA Starter Kit, I am receiving very good opinions, but that the installation of the tools is heavy and with many alerts. Also, right now, 38 vulnerabilities.

If it were smaller and without alerts, it would make entry easier.

**Comment by TimvdLippe** [comment]
If I remember correctly, the biggest contributors are WCT and puppeteer (it downloads a local installation of Chromium for every installation)

**Comment by rictic** [comment]
I'm working on fixing the vulnerabilities now.

**Comment by abdonrd** [comment]
Great, thanks @rictic!

**Comment by abdonrd** [comment]
Any news?

**Comment by abdonrd** [comment]
Closing and old issue.
