### ISSUE TITLE
Polymer build command now shows error when testing output: Failed to execute 'define' on 'CustomElementRegistry'

### ISSUE THREAD

**Issue by nick-jonas** [Polymer/tools#379]
I'm migrating [this component](https://github.com/googlecreativelab/obvi) to Polymer 3+, and part of the component is including an option for a bundled/single-file component to host on CDNs.   I was using this command before to generate it:

```polymer build --js-minify --css-minify --bundle --name dist --entrypoint voice-button.js```

*(pre-migration the entrypoint was voice-button.html)*

Now, when I run that command, I get the following error when testing it:

```(index):1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry at https://127.0.0.1:8081/components/@polymer/polymer/lib/elements/dom-module.js:146:16```

I'm not exactly sure how to debug this further - is this an issue with the build command & latest Polymer?

**Comment by moderndeveloperllc** [comment]
Same error as #125. What version of polymer-cli are you using? This looks like it was fixed in a `pre` bild, so is it possible you are using an old version?

**Comment by dougchestnut** [comment]
I am getting the same error using the cli to create a new polymer-3-element.

I'm using polymer-cli 1.7.1

I create a new component using `polymer init` and selecting polymer-3-element
`polymer serve` gives starts up my server and gives me a url for my reusable component.
When trying the url in a browser I get: 
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry at http://127.0.0.1:8081/components/@polymer/polymer/lib/elements/dom-module.js:146:16
```

**Comment by nick-jonas** [comment]
@moderndeveloperllc I'm using polymer-cli 1.7.1

**Comment by jsilvermist** [comment]
Try viewing this from the `http://127.0.0.1:8081` url, not inside the components directory, and see if this issue persists.

**Comment by dougchestnut** [comment]
@jsilvermist That works, hmm, have always used that reusable components link when building elements.  I'll move forward with the applications url. Thanks!

**Comment by nick-jonas** [comment]
@jsilvermist it seems to still happen for me on the applications url:

```https://127.0.0.1:8081/```

The error:

```
(index):1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at https://127.0.0.1:8081/node_modules/@polymer/polymer/lib/elements/dom-module.js:146:16
```

This is how I'm linking to it in my index file (is this wrong?):

```
<script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js"></script>
<script type="module" src="./build/dist/voice-button.js"></script>
```

**Comment by nick-jonas** [comment]
@jsilvermist You're right - thanks!
