### ISSUE TITLE
[polymer-cli] Build completing, but polymer serve error: Super expression must either be null or a function

### ISSUE THREAD

**Issue by atomikolex** [Polymer/tools#382]
CLI-Version: 1.7.2
Polymer version: 3.0.2
Chrome version: 66

Trying build presets, for `polymer build --preset es5-bundled` and for `polymer build --preset es6-bundled`, build is completing, but when serving the build with polymer serve I am receiving this error
`(index):804 Uncaught TypeError: Super expression must either be null or a function
    at Object.q.inherits ((index):597)
    at start-seite.js:8
    at start-seite.js:179
    at f ((index):795)
    at (index):786
    at h ((index):810)
    at h ((index):810)
    at e ((index):785)
    at i ((index):818)
    at (index):829
`
For `polymer build --preset uncompiled-bundled` I am receiving `Uncaught ReferenceError: PolymerElement is not defined` when serving with polymer serve. 
Without bundling the test app is running without issues in Chrome 66 and Firefox 60.

Edit: When running the `es6-unbundled` preset, I can serve the build without errors, and just receive [violation] warnings. Am I doing something stupid here or is this just not reproducible?

**Comment by majpiotr** [comment]
Description:
The same issue here, but I've figured out what causes it: multiple invocations of:
`import('some/file.js');`

Steps to reproduce:
1. In fresh polymer-3-starter-kit, in my-app.js file for example, add one more import statement, like this:
```
      case 'view404':
        import('./my-view404.js');
        import('./my-view404.js');
        break;
```
2. run `polymer build`
3. run `polymer serve build/es5-bundled/ --open` or `polymer serve build/es6-bundled/ --open`
4. there should be errors in the console when clicking on links and no pages content will appear.

Environment:
polymer-cli: v1.7.3
Polymer: v3.0.2
webcomponents: v2.0.0
Chrome 67 on Linux

This problem doesn't occur when using polymer-cli@next (i believe it's 3.0.0-pre12) for building.

**Comment by qertis** [comment]
+1
