### ISSUE TITLE
Minify JSON files

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [Polymer/tools#383]
Since JSON is a subset of JavaScript object notation (all JSON-formatted text is also syntactically legal JavaScript code), what about also minify *.json (not only *.js) files such as `manifest.json`, `push-manifest.json`, etc. during build to reduce final web app size?

**Comment by rictic** [comment]
There's not a ton that you can do to minify json while keeping the exact same semantics. `JSON.stringify(JSON.parse(rawInput))` would at least remove the whitespace though.
