### ISSUE TITLE
[cli] Add an option to rename "node_modules" folder

### ISSUE THREAD

**Issue by Dabolus** [Polymer/tools#384]
App Engine doesn't upload any directories (and subdirectories) that contain "node_modules". It would be great to have an option to rename the ouput "node_modules" folder (and of course all the references to it) to something else (e.g. "node_assets" like in the new [pwa-starter-kit](https://github.com/Polymer/pwa-starter-kit/blob/af8d2856749f1dfad9ee61e9c9a1640651e16d10/package.json#L12))

**Comment by justinfagnani** [comment]
Yeah, it'd be great to get rid of the custom step just for App Engine Flex. Note that the new node.js standard runtime allows for a custom ignore file, so we don't have to do that step.
