### ISSUE TITLE
Error when globally installing CLI 1.7.2

### ISSUE THREAD

**Issue by jordanfinners** [Polymer/tools#386]
Hello, I've tried to update the cli globally and get this error due to permissions when attempting to install.

This is causing me issues running the tools properly. Here is a snippet from the npm logs

32245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
32245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
32245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
32245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
32246 verbose stack Error: wd@1.6.2 install: `node scripts/build-browser-scripts`
32246 verbose stack Exit status 1
32246 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
32246 verbose stack     at EventEmitter.emit (events.js:182:13)
32246 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
32246 verbose stack     at ChildProcess.emit (events.js:182:13)
32246 verbose stack     at maybeClose (internal/child_process.js:957:16)
32246 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
32247 verbose pkgid wd@1.6.2
32250 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "polymer-cli"
32251 verbose node v10.1.0
32252 verbose npm  v6.0.1
32253 error code ELIFECYCLE
32254 error errno 1
32255 error wd@1.6.2 install: `node scripts/build-browser-scripts`
32255 error Exit status 1
32256 error Failed at the wd@1.6.2 install script.

**Comment by rictic** [comment]
`sudo npm install` is a strong antipattern. Super, super unsafe!

If you really really wanna continue installing that way, does globally installing `wd` fail?
