### ISSUE TITLE
Using es modules in HTML Imports

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/tools#390]
I've been playing around with using es modules inside HTML Imports, so that I can start porting over at least a part of my codebase to modules. Especially js libs. 

One of the issues I'm running into is that when you place a <script type="module"> in a HTML Import it won't wait for the other imports to load as it is deferred. This causes some required dependencies to not be available as the module runs before the dependencies are loaded. Is there any workaround for this?

**Comment by aomarks** [comment]
This is a known bug, see https://crbug.com/767841. As a workaround you can add any non-empty `<script>` tag anywhere in your document, and that will force other scripts to wait for the HTML imports to load.
