### ISSUE TITLE
Babel v7 (rc) prevents the custom elements polyfill from finding element definitions.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/tools#398]
#216 pins @babel/plugin-transform-classes to a particular version to avoid a problem with the way that they transformed classes extending built-in constructors. babel/babel#7533 fixes this problem. Once it's in a tagged release, we should revert #216.

**Comment by javatheist** [comment]
The mentioned babel bug #7533 has been merged into master already. Pls revert #216.

**Comment by bicknellr** [comment]
That PR was merged but isn't in any release yet, AFAICT.

**Comment by coreyfarrell** [comment]
babel just released 7.0.0-beta.48 today, should include the fix.

**Comment by web-padawan** [comment]
I am trying 7.0.0-beta.49 and still getting the errors like this:
```
Class constructor CustomStyle cannot be invoked without 'new'
```

Has someone been able to run latest `@babel/preset-env` with a `babel-loader`? Trying to get Webpack working now and got stuck on that issue.

**Comment by bicknellr** [comment]
babel/babel#7533 actually didn't end up fixing this issue. [The function they use in place of `Reflect.construct`](https://github.com/babel/babel/blob/9f4e2f81d8c1780ba435e880479427f45213421a/packages/babel-helpers/src/helpers.js#L474-L481) causes `this.contructor` to be wrong when calling into the polyfilled `HTMLElement` constructor. This prevents the polyfill from finding the definition, which it needs to either create an element with the correct tag name or return the already existing element that's being upgraded. I'm not sure of a good workaround or potential fix to send to Babel yet.

**Comment by bicknellr** [comment]
Hmm, maybe `Function.bind.toString` would help here? If we asked them to actually call `Class` from that snippet with `apply` if `Class.toString()` doesn't end with `{ [native code] }`, would that still guarantee they always constructed native stuff with `new`?

**Comment by web-padawan** [comment]
Referenced this issue from the relevant `lit-element` issues. 
/cc @TimvdLippe

**Comment by web-padawan** [comment]
@bicknellr I have tried to update `@babel/plugin-transform-classes` to 7.0.0-beta.52, and I no longer see the errors with the `new`. Wondering if babel/babel#8100 could fix the problem.

**Comment by bicknellr** [comment]
I think the reference in that commit which auto-closed this issue actually refers to the original here: https://github.com/Polymer/polymer-modulizer/issues/398.

**Comment by moderndeveloperllc** [comment]
@bicknellr Should this issue be renamed? That commit is released, but @web-padawan indicates the issue persists.

**Comment by web-padawan** [comment]
@bicknellr just to clarify: do I understand correctly that with the `Reflect.construct` based native shim landed in CE polyfill 1.2.0 this plugin is no longer required to be pinned?

**Comment by web-padawan** [comment]
@bicknellr @justinfagnani I was wondering if you have any plans regarding this issue? Babel is now RC and we still have to pin the plugin version, and looks like there is no opened ticket in their repo. 

As you have more understanding about what behaviour is needed, and can formulate it better, could you submit the issue there? Also, do I understand correctly that it is only needed for IE11 now, as the native-shim uses `Reflect.construct` and therefore should work fine when transpiled to ES5?

**Comment by justinfagnani** [comment]
@bicknellr could you file a new issue on Babel with the small repro we were working on?

@web-padawan another development here is that we don't need this transform as much because we made a new custom-elements-es5-adapter shim that works with both ES5-style classes and real classes. @bicknellr has that been released with the polyfills yet?

**Comment by bicknellr** [comment]
Filed: https://github.com/babel/babel/issues/8496

**Comment by hzoo** [comment]
There's a fix https://github.com/babel/babel/pull/8501 if anyone wants to verify

**Comment by bicknellr** [comment]
Sorry, I've been trying to verify this but I'm having trouble using `npm link` to set up our tools with a locally built version of Babel.

**Comment by hzoo** [comment]
Could also copy the diff in https://github.com/babel/babel/pull/8501/files#diff-f3afc82f08eb675b17f723219bd1ee36 if thats easier since its just the helper change?
