### ISSUE TITLE
[polymer-cli] Executing build programmatically fails while it works via cmd line

### ISSUE THREAD

**Issue by hvdb** [Polymer/tools#401]
Hello,

We updated our build system to polymer-cli 1.7.2 and 8.11.2
And our builds are now failing with this error:

```
 new dependency analyzed, pushing into dependency stream... /Users/hvdb/Developer/Gitlab/fruitloops/picard-application-build/tmp/packages/app/src/pages/view.html
[21:30:00] 'picard-fl-build' errored after 1.62 min
[21:30:00] Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:240:30)
    at PassThrough.Readable.push (_stream_readable.js:208:10)
    at PassThrough.Transform.push (_stream_transform.js:147:32)
    at BuildAnalyzer.dependencyPathAnalyzed (/Users/hvdb/Developer/Gitlab/fruitloops/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:425:34)
    at Promise (/Users/hvdb/Developer/Gitlab/fruitloops/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:483:45)
    at new Promise (<anonymous>)
    at StreamLoader.<anonymous> (/Users/hvdb/Developer/Gitlab/fruitloops/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:476:20)
    at Generator.next (<anonymous>)
    at /Users/hvdb/Developer/Gitlab/fruitloops/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:20:71
    at new Promise (<anonymous>)
error Command failed with exit code 1.
```
(line numbers can be a bit off due to extra logging rules)

It fails only when we use the polymerCLI programmatically to execute the build.
```
const polymerCli = new polymerCLI.PolymerCli(['build'], json);
 return polymerCli.run();
```
(json is the polymer json, we have some optional custom code for changing the bundling strategy. If I remove json and just use the default polymer.json (same as spawn) it still fails.)

This worked up until polymer-cli 1.6.0 (polymer-build 2.5.0)

The dependency stream is already closed but it's not ready yet.
This problem however does not occur when we execute it in a child process for instance.

If we spawn a process to execute polymer build, it works fine.

```
 const spawn = require('child_process').spawn;
    let child = spawn('polymer', ['build']);
    child.on('close', function (code) {
        console.log('child process exited with code ' + code);
    });
  });
```
  
Any ideas what can cause this problem?
I am debugging it but haven't had any success yet.

Henk

**Comment by usergenic** [comment]
The only thing I can think of at the moment which could explain the child process behavior is possibly due to the Analyzer now relying on synchronous node package resolution function `resolveSync` that works only on the filesystem, and which may possibly (I need to check the code) have some per-process optimizations/features that might be effected by spawning processes.

It might be useful to understand more about your config.  Can you share a copy, redacted-or-otherwise?

**Comment by korzio** [comment]
@usergenic 
I think you are close with a `resolveSync`
I've tried to create a minimal [sample code with a reproducible error](https://github.com/korzio/Polymer-tools-issues-401)

That happens with `lazy-import` dependencies in our case. So we've found out that there are 2 issues:
1. The `domain` - specific error handling (we fixed it locally for ourselves, but the code needs to be revised)
2. The `lazy-import` build/analyze error. In our case that resolved url was incorrect (it could not be taken from a `lazy-imported` dependency)

@see https://github.com/korzio/Polymer-tools-issues-401

**Comment by usergenic** [comment]
@hvdb let me know if you have had any success working around this.  I'll see if I can reproduce your error today with a fresh project.

**Comment by usergenic** [comment]
@korzio fwiw, this is my result from `npm test`.  Note that I did the bower install but then also tried an npm install inside my-app.  According to the dependencies of your package.json, you're trying to get `@polymer/polymer ^2.0.0` which will not resolve to the `3.x` major version, and hence, you will not get polymer-element.js you only get polymer-element.html etc...

Are you trying to use polymer 3 or 2?

```bash
λ npm test

> Polymer-tools-issues-401@1.0.0 test /home/brendanb/src/github.com/korzio/Polymer-tools-issues-401
> node index.js

info: [cli.command.build]    Clearing build/ directory...
info: [cli.build.build]    (default) Building...
Could not resolve module specifier "@polymer/polymer/polymer-element.js" in file "/home/brendanb/src/github.com/korzio/Polymer-tools-issues-401/my-app/src/my-app-app/my-app-app.js".
```

**Comment by usergenic** [comment]
@hvdb the `.run()` is an async command, is there a chance the code isn't waiting for it to resolve?

**Comment by hvdb** [comment]
Hello,

It's waiting to resolve so that's not the problem.
Yes we managed to implement a workaround (found by @korzio)

We also saw this issue coming with polymer-cli 1.5.2 & node8.
(Only when source maps was set to true)

So the problem exists only with node8.
We found a workaround and @korzio did some research into the issue.

Setting usingDomains for events to false fixed the issue.
```
require('events').usingDomains = false;
```

Here is some background information:

# Difference between Node@8 and Node@6 flows

## Node@6

Log for rejected file

```
geting /picard-application-build/tmp/packages/app/src/pages/view.html
undefined
geting promise /picard-application-build/tmp/packages/app/src/pages/view.html
rejecting /picard-application-build/tmp/packages/app/src/pages/view.html
Error: stream.push() after EOF
at readableAddChunk (_stream_readable.js:156:17)
at PassThrough.Readable.push (_stream_readable.js:134:10)
at PassThrough.Transform.push (_stream_transform.js:128:32)
at BuildAnalyzer.dependencyPathAnalyzed (/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:430:34)
at err (/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:509:45)
at StreamLoader.<anonymous> (/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:495:20)
at next (native)
at /picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:20:71
at __awaiter (/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:16:12)
at StreamLoader.load (/picard-application-build/node_modules/polymer-cli/node_modules/polymer-build/lib/analyzer.js:476:16)
rejected /picard-application-build/tmp/packages/app/src/pages/view.html
```

Flow

```
promise
-> try
-> stream.error()
-> catch
```

---

## Node@8

Log

```
geting /picard-application-build/tmp/packages/app/src/pages/view.html
undefined
geting promise /picard-application-build/tmp/packages/app/src/pages/view.html
[14:11:52] 'picard-fl-build' errored after 1.7 min
[14:11:52] Error: stream.push() after EOF
```

Flow

```
promise
-> try
-> stream.error
-> domain.error
-> asyncDone (gulp async and other libraries)
-> ...
-> exit(1)
```

## Why?

Node@8 enters [a domain](https://nodejs.org/api/domain.html#domain_implicit_binding)
The domain is active in the moment when the stream is created

```js
this.domain = null;
if (EventEmitter.usingDomains) {
// if there is an active domain, then attach to it.
domain = domain || require('domain');
if (domain.active && !(this instanceof domain.Domain)) {
this.domain = domain.active;
}
}
```

Node@6 doesn't enter [the domain](https://nodejs.org/api/domain.html#domain_implicit_binding)
The domain is NOT active at the moment when the stream is created

## Why the domain is active?

`EventEmitter.usingDomains` is set to `true`
It happens asyncronously somewhere deep in a system and can be ignored for the investigation because it can happen anywhere anytime in a code except it's forbidden to override in a property descriptor (@see `defineProperty`) in the internal [`events` node module](https://github.com/nodejs/node/blob/fe8794560a22cc62a482bf071e2050ce1ea6ea3e/lib/events.js#L34).

# Hotfix

As the `EventEmitter.usingDomains` behavior should not be hardly controlled, the best hotfix would be temporary set the `EventEmitter.usingDomains` to `false` before running a build.

**Comment by hvdb** [comment]
@usergenic :)
