### ISSUE TITLE
`polymer lint` breaks when there is an empy style block

### ISSUE THREAD

**Issue by manolo** [Polymer/tools#408]
Create a `m-test.html` file with the content:

```html
<dom-module id="m-test">
  <template>
    <style></style>
  </template>

  <script>
    class MTest extends Polymer.Element {
      static get is() {
        return 'm-test';
      }
    }
    window.customElements.define(MTest.is, MTeste);
  </script>
</dom-module>

```

Then run  `polymer lint --rules polymer-2 --input m-test.html` breaks with the following error  and exit code 1.

`m-test.html(1,1) warning [internal-lint-error] - Internal error during linting: Cannot read property '__location' of undefined`

Removing the `<style>` block or setting some comment e.g. `/*  */` linter passes

Problem seems introduced in polymer-cli `v1.7.x`

**Comment by kobleistvan** [comment]
Up

**Comment by billy-hardy** [comment]
another format around this is to have the style tag span 2 lines
```
<style>
</style>
```

A fix to the tool would be appreciative though

**Comment by barnomics** [comment]
At least, I _think_ its the same issue.  The output is making it impossible to narrow down where this is happening.   I remove `iron-pages` to debug - the next line throws the error.  So on and so forth... 

```
<link rel="import" href="../../bower_components/iron-pages/iron-pages.html">
~

app/elements/my-page.html(1,1) warning [internal-lint-error] - Internal error during linting: Cannot read property '__location' of undefined
```

**Comment by barnomics** [comment]
Also if it helps debug... I'm working on a Polymer 1 project.  

The warning throws in the  `"rules": ["polymer-2-hybrid"]` but not in `"rules": ["polymer-1"]`

**Comment by barnomics** [comment]
Oh it appears my "empty" style issues are coming from importing style modules...

```
<dom-module id="new-element">
  <template>
    <style include="my-style-module"></style> <!-- i'm breaking lint -->
  </template>
</dom-module>
```

**Comment by ankon** [comment]
Somewhat amazingly it seems this bug can be worked-around by documenting the work-around ...
```diff
diff --git a/index.html b/index.html
index 9beb622..ce1795e 100644
--- a/index.html
+++ b/index.html
@@ -19,7 +19,7 @@
 				<dom-bind>
 					<template>
 						<custom-style>
-							<style include="demo-pages-shared-styles"></style>
+							<style include="demo-pages-shared-styles"><!-- https://github.com/Polymer/tools/issues/408 --></style>
 						</custom-style>
 
 						<paper-bottom-sheet slide="{{sliding}}" modal="{{modalSheet}}" with-backdrop="[[withBackdrop]]" id="sheet">
```
