### ISSUE TITLE
HTML template result linting / validation

### ISSUE THREAD

**Issue by thescientist13** [Polymer/tools#427]
Opening per recommendation in the [lit-html](https://github.com/Polymer/lit-html/issues/350#issuecomment-393687459) repo

### Summary
A nice feature of JSX / React / ESLint was that if an HTML tag was missing it's closing tag (for example) a linting error could be raised, ex.
```shell
 @ ./.cache/sync-requires.js 30:67-185

 WAIT  Compiling...                                                                                                                 10:17:16

 ERROR  Failed to compile with 1 errors                                                                                             10:17:17

 error  in ./src/pages/blog/2018/06/01/index.jsx

Syntax Error: Expected corresponding JSX closing tag for <p> (24:8)

  22 |             we would be happy to have you join the convesation<p>
  23 |
> 24 |         </div>
     |         ^
  25 |       </BlogPost>
  26 |     );
  27 |   }



 @ ./.cache/sync-requires.js 30:67-185
```

I notice that unclosed tags seem to "fail" silently when using **lit**.  

I guess this is just to raise the issue here to see if this is something that would possible, or is maybe already a solved somewhere I didn't find?  (maybe it could be built on top of **lit**, or maybe it should be an ESLint preset or something like that?)

All thoughts / feedback welcome + appreciated!

**Comment by wernight** [comment]
This IMO is actually one of the major drawbacks of lit-html. When JS is moving toward more and more compilation type checks, lit-html seems dragging behind here. Relying on IDE isn't a solution.

**Comment by joeyJsonar** [comment]
Dont know why this is closed, but this looks like a very important feature. It is so easy to accrue technical debt on unreadable stringified html template. I suggest to re-open this.
