### ISSUE TITLE
addPushManifest treats app dependencies as siblings

### ISSUE THREAD

**Issue by keanulee** [Polymer/tools#433]
Shop#master (Polymer 2.0) uses the `es6-unbundled` preset which uses the `addPushManifest` build configuration. Today, running `polymer build` generates a push-manifest.json that references dependencies as siblings:

```js
{
  "src/shop-app.html": {
    "../polymer/polymer-element.html": {
      "type": "document",
      "weight": 1
    },
```

### Expected

Previously, they are correctly referenced as files within `bower_components`:

```json
{
  "src/shop-app.html": {
    "bower_components/polymer/polymer-element.html": {
      "type": "document",
      "weight": 1
    },
```

This regressed sometime during the run-up to the Polymer 3.0 release.

**Comment by d4l3k** [comment]
`yarn global add polymer-cli@1.6.0` works correctly.

**Comment by aomarks** [comment]
This should be fixed in polymer-cli 1.7.4 [released yesterday](https://github.com/Polymer/tools/blob/master/packages/cli/CHANGELOG.md).

**Comment by d4l3k** [comment]
Nice! Thanks @aomarks!

**Comment by aomarks** [comment]
Hi @d4l3k :)
