### ISSUE TITLE
Inject code for registering service worker during build

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/tools#437]
I find it strange that `polymer build --add-service-worker` will generate the service worker code for you but doesn't do anything to make sure it is actually registered. Right now, you have to manually add `navigator.serviceWorker.register("service-worker.js");` to your index.html which errors out if you're loading a build that doesn't include the service worker.

Is there any reason why `polymer build` shouldn't take care of adding that code for you?

**Comment by jsilvermist** [comment]
I for one would absolutely want this to be opt-in if added, as I use `polymer-cli` to generate the service worker, but use a slightly more complicated register to allow hooks for toast notifications.

If you are getting errors, just add an empty service worker js file for while developing on local, then it will be overwritten on build.

**Comment by MaKleSoft** [comment]
> a slightly more complicated register to allow hooks for toast notifications
@jsilvermist I'd be interested to look at that code if you don't mind sharing it. I'll probably need to make some adjustments to the service worker as well but there is no documentation on how to do that.

**Comment by jsilvermist** [comment]
The registration code I'm using is pretty similar to what's used for the Polymer docs site as seen here: https://github.com/Polymer/docs/blob/24fd220e49620d10cb9b33158a6eff38a9425a28/app/js/app.js#L61-L96

The code I'm using to register the service worker is:
```js
// Register service worker, if supported, after the load event.
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {

    navigator.serviceWorker.register('service-worker.js', {
      scope: document.querySelector('base').getAttribute('href'),
    })
    .then((registration) => {
      registration.onupdatefound = () => {
        // The `updatefound` event implies that `registration.installing` is set.
        // More info: https://w3c.github.io/ServiceWorker/
        const installingWorker = registration.installing;
        installingWorker.onstatechange = () => {
          switch (installingWorker.state) {
            case 'installed':
              if (!navigator.serviceWorker.controller) {
                window.dispatchEvent(new CustomEvent('show-toast', {
                  detail: {
                    text: 'Service worker installed, site is cached for offline use.',
                  },
                }));
              }
              break;
            case 'redundant':
              throw Error('The installing service worker became redundant.');
          }
        };
      };
    })
    .catch((error) => {
      console.error('Service worker registration failed:', error);
    });

    // Check to see if the service worker controlling the page at initial load has
    // become redundant, since this implies there's a new service worker with fresh content.
    if (navigator.serviceWorker.controller) {
      navigator.serviceWorker.controller.onstatechange = (event) => {
        if (event.target.state === 'redundant') {
          window.dispatchEvent(new CustomEvent('show-toast', {
            detail: {
              text: 'Site updated. Refresh this page to see the latest content.',
              duration: Infinity,
              button: {
                text: 'Refresh',
                onclick: () => window.location.reload(true),
              },
            },
          }));
        }
      };
    }

  });
}
```

**Comment by MaKleSoft** [comment]
@jsilvermist Thanks!
