### ISSUE TITLE
pull-all optionally via HTTPS instead of SSH

### ISSUE THREAD

**Issue by ssorallen** [Polymer/tools#44]
As recommended by GitHub, I tend to [clone repos via HTTPS](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended) rather than via SSH. The pull-all.sh script always passes the [`-s` flag](https://github.com/Polymer/tools/blob/master/bin/pull-all.sh#L20) to Bigstraw, which forces it to use SSH. It'd be nice optionally allow HTTPS (and keep the default via SSH for backwards compatibility).

**Comment by azakus** [comment]
The problem is more to do with how authentication is handled. It's pretty much impossible to have N>1 password prompts on a command line interface.

You can use some of these "permanent" auth techniques: https://confluence.atlassian.com/display/STASH/Permanently+authenticating+with+Git+repositories,
but that requires setup on the user side.

**Comment by ssorallen** [comment]
If you're on OS X, you [cache your GitHub credentials](https://help.github.com/articles/caching-your-github-password-in-git/) in the OS X Keychain and allow Git access to your Keychain. Once you allow access one time, you're set.

If there aren't similar solutions for other platforms I can see it being a big pain.

**Comment by ssorallen** [comment]
SSH requires setup by the user too. Create an SSH key, upload to GitHub, etc.

**Comment by azakus** [comment]
While true, there's far less setup involved for that in my opinion.

**Comment by ssorallen** [comment]
That's fair, and that's why I titled this "optionally" since everyone sets up Git differently. Right now the script always uses SSH without an option for other protocols. It'd be great to have the option to use HTTPS instead.

**Comment by frankiefu** [comment]
Agree.  The default should be SSH and should have an option to pass in to use HTTPS.
