### ISSUE TITLE
nomodule attribute and amd module transpilation

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/tools#495]
In my application I'm I adding the es2015 polyfill for es2015 functions functions like Array.protoype.includes etc. I use the nomodules attribute, which is a nice indicator to know that we can skip loading it on browsers that support es2015. This causes the amd loader polyfill to think that the amd loader doesn't need to be injected which results in a broken build when transformModulesToAmd is set.

If the transformModulesToAmd flag is set to true, shouldn't the build always assume it should do the transformation and inject the loader?

**Comment by aomarks** [comment]
Yeah, this is a kind of crude heuristic we use to switch off the AMD transform on a per-file basis: https://github.com/Polymer/tools/blob/master/packages/build/src/html-transform.ts#L94

Maybe we should have a file glob in the config file to support per-file transformation instead, although I'd prefer we didn't have to make the config file more complicated.

@TimvdLippe I remember discussing this with you -- any thoughts? Is it actually important that we can switch off the AMD transform per file, or did we add this heuristic before we had a global flag or something?

**Comment by TimvdLippe** [comment]
Hm. This is tricky. I remember running into this issue, but sadly i don't remember the conclusion of our discussion 😢 I think most heuristics will fail, so you eventually end up with the per-file transformation. I think this should be opt-out rather than opt-in though, since the opt-out case is more rare (maybe just `index.html`?)

**Comment by LarsDenBakker** [comment]
Opt-out would be fine... but if you're already turning on transformModulesToAmd in the config, what's the use case for still wanting it to be skipped>

**Comment by LarsDenBakker** [comment]
This is still an issue for us.
