### ISSUE TITLE
polymer cli v1.7.2 npm audit issues

### ISSUE THREAD

**Issue by AxoSal** [Polymer/tools#497]
There are some vulnerability issues according to npm audit command

**Comment by web-padawan** [comment]
Duplicate of #425

**Comment by AxoSal** [comment]
@web-padawan I get 30 vulnerabilities (18 low, 5 moderate, 5 high, 2 critical) after "npm audit fix" and this is regarding polymer-cli, not polymer-build

**Comment by web-padawan** [comment]
Yep, I mentioned #428 which is correct issue. Lots of issues are now under the tons of editor-service stuff :sad:

**Comment by TimvdLippe** [comment]
Yup, this is a duplicate of #428
