### ISSUE TITLE
Polymer serve started to give "Failed to resolve module specifier" error after Chrome Update

### ISSUE THREAD

**Issue by fenerlee1907** [Polymer/tools#501]
Hi,

I was trying to create a new Polymer 3.0 component by following the guide at: [https://www.polymer-project.org/3.0/start/first-element/intro](https://www.polymer-project.org/3.0/start/first-element/intro)

It was working fine when I tried to use command "polymer serve". 
(
  Steps I followed were:
  1 - npm install -g polymer-cli
  2 - git clone https://github.com/PolymerLabs/polymer-3-first-element.git
  3 - cd polymer-3-first-element
  4 - npm install
  5 - polymer serve 
)

At the weekend, I restarted my Mac, updated MacOS to 10.13.5 and Chrome to Version 67.0.3396.79 (Official Build) (64-bit). I am not sure what the reason is but when I try to open the demo page in my browser, I got this error:

**Uncaught TypeError: Failed to resolve module specifier "@polymer/polymer/polymer-element.js". Relative references must start with either "/", "./", or "../".**

Is there anybody facing the same problem after these updates? I now cannot even run the most basic sample when I follow the guide provided by Polymer team. I really need your help. Thanks.

**Comment by jsilvermist** [comment]
Are you trying to view this from the components dir or the base dir?

Try to view the demo at the base `/demo` path.

**Comment by web-padawan** [comment]
Make sure you use `polymer serve --npm`

**Comment by fenerlee1907** [comment]
I am running "polymer serve" from components main folder where package.json and polymer.json exist. I also tried using /demo path but no luck. When I try to run it with --npm option, I got this error in the console.

`error:   Uncaught exception: UNKNOWN_OPTION: Unknown option: --npm
error:   UNKNOWN_OPTION: Unknown option: --npm
    at halt (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:81:15)
    at Argv.validate (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/argv.js:72:7)
    at CommandLineArgs.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-args/lib/command-line-args.js:57:10)
    at CommandLineCommands.parse (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-commands/lib/command-line-commands.js:78:28)
    at PolymerCli.run (/usr/local/lib/node_modules/polymer-cli/lib/polymer-cli.js:122:35)
    at /usr/local/lib/node_modules/polymer-cli/bin/polymer.js:22:7
    at /usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:46:14
    at process (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/polymer-cli/node_modules/resolve/lib/async.js:69:43)`

**Comment by jsilvermist** [comment]
What does it give if you run `polymer --version`?

**Comment by fenerlee1907** [comment]
Version is 0.8.0. I just ran "npm install -g polymer-cli" in order to install by the way.

**Comment by jsilvermist** [comment]
There's your problem, that version is way too old, try typing `which polymer` to see where it's getting the command from.

I would assume that somehow your node directories got messed up while updating MacOS.

**Comment by fenerlee1907** [comment]
It is getting the command from "/usr/local/bin/polymer"

**Comment by fenerlee1907** [comment]
I took a quick reach but could not find anything related with NPM and MacOS Update. I am not sure if I should re-install npm or not. Do you suggest anything about it?

**Comment by jsilvermist** [comment]
Well at least try to reinstall the Polymer CLI to get the newer version.

For me, I would install nvm, then use nvm to install the latest version of node 9, then install the Polymer CLI.

Alternatively, you could try installing the Polymer CLI locally in your project, then check the version and try serving again.

**Comment by fenerlee1907** [comment]
@jsilvermist Thank you for you recommendations. I uninstalled polymer-cli, npm and node and everything is fine now. My Polymer version in 1.7.2.

Strange thing is I really have no idea about the reason behind this. Anyway, it is working now ;)

**Comment by intcreator** [comment]
I'm having this same issue with Polymer CLI 1.7.4 on Node 10.

**Comment by jsilvermist** [comment]
@fenerlee1907 I don't think 1.7.4 will work on Node 10 atm, but it should NOT be the same issue.

To follow support for Node 10, check out https://github.com/Polymer/tools/pull/536.

**Comment by intcreator** [comment]
@jsilvermist it ended up working for me.  I think I ran `modulizer` with package names the first time through then wasn't able to serve anything.  I ran it again with paths and I think that fixed it (or will, once I error check the automatically generated paths).
