### ISSUE TITLE
[polymer-test] error with Chrome 66 and 67

### ISSUE THREAD

**Issue by felixzapata** [Polymer/tools#509]
Hi all, when I launch my tests, the browser window it looks like broken.

`polymer test -l chrome --npm`

I use `"web-component-tester": "^6.6.0"` as a `devDependency`.

![captura de pantalla 2018-06-12 a las 10 19 39](https://user-images.githubusercontent.com/997038/41278523-527a408e-6e2a-11e8-9222-44bdd86957df.png)

![captura de pantalla 2018-06-12 a las 11 26 10](https://user-images.githubusercontent.com/997038/41283123-0d58acf0-6e36-11e8-9a09-50576693f457.png)

![captura de pantalla 2018-06-12 a las 12 04 17](https://user-images.githubusercontent.com/997038/41284183-de43beca-6e38-11e8-884b-47823d34c603.png)

I can't see the results of the test on it neither open the console to debug. This happen to another colleague of my team.

This happen with chrome 66 and 67.

My version of Polymer Cli is 1.6.0. It also happens with version 1.7.2.

**Comment by TimvdLippe** [comment]
Could you provide a reproduction case which allows us to inspect it? This can be a GitHub repo with setup instructions if that is easier for you.

**Comment by felixzapata** [comment]
hi, I am going to try to describe the configuration because after three hours of work, I've tested dozens of combinations in order to try to fix it. My currently my configuration is:

+ Node 8.0.0 (I was using Node < 8 but I have had to update in order to try with Polymer cli 1.7.x)
+ Polymer 1.x
+ Polymer cli 1.7.2
+ Chrome v67.x
+ Inside the `package.json` of the project:

```
"devDependencies": {
    "wct-browser-legacy": "^1.0.1",
    "web-component-tester": "^6.6.0"
  }
```

My colleague has:

+ Node < 8
+ Polymer 1.x
+ Polymer Cli 1.6.x
+ Chrome v66.x
+ Inside the `package.json` of the project:

```
"devDependencies": {
    "web-component-tester": "^6.6.0"
  }
```
`wct-browser-legacy` as far as I know it is only need it with Polymer Cli 1.7.x.

We obtain the same error with `"web-component-tester": "^6.5.0"`.

We run the tests with:

`polymer test -l chrome --npm`
`polymer test -l firefox --npm` (the only problem with firefox is that there is no output of the console lines)

We did not not have this problem a few days ago and we have not made any changes in our platform related with the versions of the libraries related with the tests.

**Comment by TimvdLippe** [comment]
> Polymer 1.x

I do not think you should be testing with the `--npm` flag, as Polymer 1 still used HTML imports and Bower. You can test this yourself by using `polymer serve` and inspect the test page yourself

**Comment by felixzapata** [comment]
I'm going to try to reproduce the error using the same configuration with the tests inside of the Polymer News project (with a Polymer 1.x version).

**Comment by felixzapata** [comment]
Instead of the Polymer News, I've run the tests of the version with Polymer 1.x of the Polymer Starter Kit:

`polymer test -l chrome --npm -p`

![captura de pantalla 2018-06-12 a las 13 55 32](https://user-images.githubusercontent.com/997038/41288973-7bef78ee-6e48-11e8-985b-cffd8b1b37c2.png)

I've modified the `package.json` file adding:

````
"wct-browser-legacy": "^1.0.1",
"web-component-tester": "^6.6.0"
````

And then, in test/index.html, I've replaced `<script src="../bower_components/web-component-tester/browser.js"></script>` with `<script src="../node_modules/web-component-tester/browser.js"></script>`.

**Comment by felixzapata** [comment]
It also happens with the master branch (Polymer 3.x) of Polymer Starter Kit. 

![captura de pantalla 2018-06-12 a las 14 28 23](https://user-images.githubusercontent.com/997038/41290609-b638da86-6e4d-11e8-9618-54b17b507fb3.png)

and with version 3.2.1 of Polymer Starter Kit (with Polymer 2.x):

![captura de pantalla 2018-06-12 a las 14 37 12](https://user-images.githubusercontent.com/997038/41290775-2aaf7046-6e4e-11e8-9053-8d30d339d0ca.png)

Both tests, just a fresh install and running the tests via command line:

`polymer test -l chrome -p`

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue, so sadly cant provide any help atm :(

**Comment by felixzapata** [comment]
but it happens with fresh install of the projects and Chromes 66 and 67. And it also happens to one of my colleagues

**Comment by jsilvermist** [comment]
It's working fine for me too, seems almost like you have something blocking it at an app level.

Do you and your colleagues all use a certain antivirus, firewall, etc?

**Comment by felixzapata** [comment]
We have the same laptop and no antiviruses, firewall. My colleague has Polymer cli version 1.6.x with Chrome 66 and I have Chrome 67 with Polymer cli version 1.7.x (and Node version 8). I had Polymer cli version 1.6.x but I updated it in order to mix this problem. 

Under Firefox the tests are fine but with Chrome we can't debug in the browser.
