### ISSUE TITLE
Migrate open issues to monorepo

### ISSUE THREAD

**Issue by dhruvdutt** [Polymer/tools#516]
Build a script to create/migrate all open issues from repositories that are moved under Polymer/tools monorepo.

Total open issues: **823**

> Each issue opened inside this repo will be namespaced with the source repository name.
>
> For instance, [polymer-cli] Polymer build: no output except for polymer.json
> 

List of repositories moved to Polymer/tools monorepo

_Open issues : polymer/[repository]_
- 220 : [polymer-cli](https://github.com/Polymer/polymer-cli)
- 204 : [web-component-tester](https://github.com/Polymer/web-component-tester)
- 129 : [polymer-analyzer](https://github.com/Polymer/polymer-analyzer)
- 80  : [polymer-bundler](https://github.com/Polymer/polymer-bundler)
- 69  : [polymer-build](https://github.com/Polymer/polymer-build)
- 47  : [polyserve](https://github.com/Polymer/polyserve)
- 45  : [polymer-linter](https://github.com/Polymer/polymer-linter)
- 20  : [wct-local](https://github.com/Polymer/wct-local)
- 8   : [wct-sauce](https://github.com/Polymer/wct-sauce)
- 1   : [tools-common](https://github.com/Polymer/tools-common)
- 0   : [browser-capabilities](https://github.com/Polymer/browser-capabilities)
- 0   : [polymer-editor-service](https://github.com/Polymer/polymer-editor-service)
- 0   : [polymer-project-config](https://github.com/Polymer/polymer-project-config)

**Comment by dhruvdutt** [comment]
I can help create a script for this if we're intending to go forward with this.

**Comment by aomarks** [comment]
We actually already have a tool for this (not published), we've run it on a few repos but not to completion yet cc @rictic
