### ISSUE TITLE
[WCT] Browser Version mistake, when LAUNCHPAD variables are set

### ISSUE THREAD

**Issue by fooloomanzoo** [Polymer/tools#528]
If the environment variable e.g. LAUNCHPAD_CHROME is set (windows), it fails to look up the version number of chrome.
E.g.: 
```
LAUNCHPAD_CHROME="C:\Program Files (x86)\Google\Chrome\Application\"
```
```
error: [cli.main]   cli runtime exception: TypeError: Cannot read property 'match' of undefined
error: [cli.main]   TypeError: Cannot read property 'match' of undefined
    at chrome (C:\Users\Knecht Ruprecht\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\wct-local\lib\browsers.js:110:36)
    at Object.<anonymous> (C:\Users\Knecht Ruprecht\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\wct-local\lib\browsers.js:84:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Knecht Ruprecht\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\wct-local\lib\browsers.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

problems are caused by this function:
```javascript
/**
 * @param browser A launchpad browser definition.
 * @return A selenium capabilities object.
 */
function chrome(browser, browserOptions) {
    return {
        'browserName': 'chrome',
        'version': browser.version.match(/\d+/)[0],
        'chromeOptions': {
            'binary': browser.binPath,
            'args': browserOptions || ['start-maximized']
        }
    };
}
```
The ```browser```-Object does not contain a version entry.

**Comment by fooloomanzoo** [comment]
A simular issue exists for firefox. Setting launchpad-envirnment-variables (espeacially the paths of the browsers) could speed up the initial load time for running tests, see: [https://github.com/bitovi/launchpad/issues/51](https://github.com/bitovi/launchpad/issues/51)

**Comment by jsilvermist** [comment]
Try using forward slashes instead?

**Comment by fooloomanzoo** [comment]
@jsilvermist No, this is just an example in markdown and not how it actually looks like. Fixed the example:
```LAUNCHPAD_CHROME="C:\Program Files (x86)\Google\Chrome\Application\"```

**Comment by hellokatili** [comment]
"bitovi/launchpad" tries to get the browser versions via [resources/ShowVer.exe](https://github.com/bitovi/launchpad/blob/master/resources/ShowVer.exe). The exec command in [version.js in line 21](https://github.com/bitovi/launchpad/blob/master/lib/local/version.js#L21) returns a "Permission denied" error. 
Because there is no error handling in this step and WTC expects a `version` in the `browser` it is not possible to run any tests.

**Comment by conceptree** [comment]
I have the same issues... it's really hard to get a proper test setup with Polymer wct structure. Is there a fix for this already?
