### ISSUE TITLE
gp.sh on Windows

### ISSUE THREAD

**Issue by AaronLayton** [Polymer/tools#53]
I was following the instructions on 

and got an error with this line when in the CMD prompt
'../tools/bin/gp.sh <username> test-element'

```
'..' is not recognized as an internal or external command, operable program or batch file.
```

Should this work in Windows?

**Comment by Scarygami** [comment]
I'm using the "Git BASH" console include with [Git for Windows](https://msysgit.github.io/) for this.

It shouldn't be too hard to create an equivalent gp.bat script to run in a normal Windows CMD prompt though.

**Comment by AaronLayton** [comment]
> It shouldn't be too hard to create an equivalent gp.bat script to run in a normal Windows CMD prompt though.

Maybe we should get one and add to this repo though as some out the box support?

**Comment by tuct** [comment]
I just ported the gp.sh to gp.ps1, and would be happy to share it.

**Comment by jahglow** [comment]
it needs to be "..\tools\bin\gp.sh" <user> element-name actually under Windows

**Comment by jahglow** [comment]
and line 23 should go `git clone git://github.com/$org/$repo.git --single-branch` if one doesn't have ssh keys installed. It's a crazy (undocumented) idea to have unnecessary prerequisites like ssh keys installed.

**Comment by tuct** [comment]
It's gp.sh <github user> <element/repo name> also on linux unless you are part of an org. I think github is forcing ssh keys for ssh connections only https will work with credentials. It would be nice to check if ssh keys are installed and if not switch to https and promt for the credentials

**Comment by tuct** [comment]
My parameters for gp.sh got swallowed, it should be 'gp.sh username element/repo'

**Comment by rictic** [comment]
Outdated, from a previous use of this repo.
