### ISSUE TITLE
[polyserve] Serving extremely slow on sinon package bundle

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/tools#538]
Serving the sinon.js bundle with `polyserve` is extremely slow (>12 seconds).

To reproduce:

1. Check out branch `fix-audit-wct-browser-legacy`
1. Install the dependencies per usual instructions
1. Run `polymer serve` in the root of this repository
1. Open http://127.0.0.1:8081/components/polymer-tools/packages/wct-browser-legacy/node_modules/sinon/pkg/sinon.js (check your port)
1. Observe that loading this particular file is extremely slow

Even when running with `polymer serve --compile never`, it remains slow. Note that other files (for example http://127.0.0.1:8081/components/polymer-tools/packages/wct-browser-legacy/node_modules/sinon/History.md) are instantly loading. Also note that after you refresh the file, it is instant again.

This leads me to believe that there is a performance issue with reading/writing ASTs to files on first load.

This issue is blocking the migration of #533

**Comment by usergenic** [comment]
polyserve and polymer serve should probably have an exclusion list for middleware that just enables pass-thru of the files which could sidestep the issue.  I'll have a go at that feature; its come up several times before and I think there's even some hardwired cruft in polyserve that already passes-thru a couple files by string-matching.

**Comment by TimvdLippe** [comment]
@usergenic Awesome, thanks for the pointer! I went ahead and opened #543, which fixed the issue for me. Back to tracking the WCT issue now.
