### ISSUE TITLE
[project-config] Uncompiled presets

### ISSUE THREAD

**Issue by ranb2002** [Polymer/tools#539]
Hi,

Is there a reason why the `uncompiled-bundled` and the `uncompiled-unbundled` presets have **es2018** in browserCapabilities instead of **es2016** in the [builds.ts](https://github.com/Polymer/tools/blob/dd1c8bbb44f37f67974fbabf878b7a495ffeb6f6/packages/project-config/src/builds.ts#L224-L249) file of project-config package?

Also, as these presets are uncompiled, should they have `module` as browser capabilities? By example, this [version](https://benjaminrancourt-int.firebaseapp.com/en) of my personal website with Polymer 3 and prpl-node-server throws an error when serving the uncompiled-bundled in Firefox 60 :
```
SyntaxError: expected expression, got keyword 'import'
```
as ES Modules are not yet completely supported in Firefox ([browser-capabilities](https://github.com/Polymer/tools/blob/dd1c8bbb44f37f67974fbabf878b7a495ffeb6f6/packages/browser-capabilities/src/browser-capabilities.ts#L118-L127)).

Finally, in the [Polymer documentaition](https://github.com/Polymer/docs/blob/master/app/3.0/toolbox/build-for-production.md), the Polymer team recommends to serve ES6 build to the browsers that supported it for better performance and `uncompiled-unbundled` 

> is suitable for serving an implementation of the PRPL pattern to browsers that use the latest JavaScript features

 Is there other gains to serve the `uncompiled` builds aside to use the latest features?

Let me know if you want me to make a pull request to update project-config.

Thanks!

**Comment by aomarks** [comment]
Uncompiled means that you could use any JavaScript feature, and it will not be transpiled, so only browsers that support all of the latest JavaScript features (ES2018 at this time) are safe to serve that to. So I think this is currently correct.

For modules, yes I think you're right, the uncompiled builds should require modules. A PR to update that would be welcome!
