### ISSUE TITLE
[WCT] wct command fails util_1.promisify is not a function

### ISSUE THREAD

**Issue by osamamaruf** [Polymer/tools#542]
## Description
The below command fails:

`wct --skip-selenium-install`

with the error:

`TypeError: util_1.promisify is not a function`

## Expected Outcome
The command should run successfully.

## Actual Outcome

The command fails with the below error : 
> wct --skip-selenium-install

TypeError: util_1.promisify is not a function

> npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
> npm ERR! node v7.10.0
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ear-ui@0.0.0 test: `wct --skip-selenium-install`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ear-ui@0.0.0 test script 'wct --skip-selenium-install'.

Log file is also attached.
[2018-06-26T05_46_55_541Z-debug.log](https://github.com/Polymer/tools/files/2135755/2018-06-26T05_46_55_541Z-debug.log)

## Additional Information
The dev dependencies are: 

>   "devDependencies": {
>     "eslint": "^4.9.0",
>     "eslint-config-airbnb": "16.1.0",
>     "grunt": "^1.0.1",
>     "grunt-contrib-clean": "^1.1.0",
>     "grunt-contrib-copy": "^1.0.0",
>     "grunt-eslint": "^20.0.0",
>     "grunt-exec": "^3.0.0",
>     "grunt-force-task": "^2.0.0",
>     "wct-headless": "^2.2.2",
>     "wct-istanbub": "^0.0.7",
>     "web-component-tester": "^6.4.0"
>   }

**Comment by TimvdLippe** [comment]
You are running on Node 7, but the tools require Node 8 or higher.
