### ISSUE TITLE
[cli] Minification does not work as expected for CSS and HTML

### ISSUE THREAD

**Issue by motss** [Polymer/tools#560]
Just realized that minification does not work as expected for Polymer 3 based apps.

Just taking `pwa-starter-kit` as an example, even though `minify` is set to true for `html` and `css` nothing has been minified actually unlike Polymer 2 where everything is minified.

https://github.com/Polymer/pwa-starter-kit/blob/a6509372e8840c9ac3928d0f6544717e1d9ba544/polymer.json#L14-L30

This got me thinking that this can be a limitation of writing HTML with template literals. But this can greatly reduce the file size if minification can be done. Not sure if what I'm trying to say makes sense.

**Comment by web-padawan** [comment]
This is a valid issue. In my Webpack starter, I use [babel-plugin-template-html-minifier](https://github.com/goto-bus-stop/babel-plugin-template-html-minifier) for that, and CLI could incorporate it as well. One detail is that it has to be included before transpiling ES6 string literals.

See the example config here: https://github.com/web-padawan/polymer3-webpack-starter/blob/master/.babelrc#L42

**Comment by motss** [comment]
@web-padawan Seems like a promising configuration. Will definitely try it out. Thanks mate
