### ISSUE TITLE
custom-elements-es5-adapter code not generated when using bundle and compile options together

### ISSUE THREAD

**Issue by zeeshanhyder** [Polymer/tools#563]
When building `compile: true ` and `bundle: true` in `polymer.json`,  custom-elements-es5-adapter code is not generated. However if i just use `compile: true` option, in that case, the code gets generated. Even if i manually put `<script src=''./node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js></script>`, this tag gets read and code is transpiled, no matter even if i `exclude` it in `compile` option. Any inputs?

Node: 8.11
Polymer CLI: 1.7.7
Polymer: 3.0.2
Webcomponents: 2.0.2

**Comment by DavidHenri008** [comment]
I have a similar case where the `<script src=''./node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js></script>` is not added to the built index.html file.
In my case, it happens when I define an exclude folder in my compile build configuration. However if I set compile at true it works.

Not Working:
```
"builds": [
    {
      "preset": "es5-bundled",
      "js": {
        "compile": {
          "exclude": ["help\\template\\scripts\\*.js"]
        }
      }
    }
  ],
```

Working:
```
"builds": [
    {
      "preset": "es5-bundled",
      "js": {
        "compile": true
      }
    }
  ],
```

Node: 8.11
Polymer CLI: 1.8.0
Polymer: 2.6.1
Webcomponents: 2.1.2

**Comment by zeeshanhyder** [comment]
I think it probably has to do with how are they reading the value of `compile` option. Setting it to any other value other than `true|false` might be causing it to break. It's very weird the issue still persists. And apparently it's not a new one. It existed before as well.

**Comment by DavidHenri008** [comment]
@jsilvermist I cannot run what you suggested since "es5" is not a valid option:
> error: [cli.main]   Promise rejection: Error: Property 'builds[0].browserCapabilities[0]' is not one of enum values: es2015,es2016,es2017,es2018,modules,push,serviceworker
