### ISSUE TITLE
Linter complains paper-listbox attr-for-selected name when placed on paper-item

### ISSUE THREAD

**Issue by dman777** [Polymer/tools#565]
When using `paper-listbox` and `attr-for-selected="value"` with `paper-item`, the  linter complains below. Is this a error on the linter part? Everything looks legit Polymer wise. It doesn't matter what name I use for the  `attr-for-selected`, it will complain. 

```
                value="[[picklistValues.ENHANCEDYESNO_DATANOTCOLLECTED]]">
                ~~~~~

src/sp-elements/sp-static-forms/sp-disabilities/sp-disabilities-form-edit.html(404,17) warning [set-unknown-attribute] - paper-item elements do not have a property named value. Consider instead:  role$
```

---------------------------

```
                <paper-listbox
                  attr-for-selected="value"
                  selected="yes"
                  class="dropdown-content">
                  <paper-item
                    value="[[picklistValues.ENHANCEDYESNO_YES]]">
                    Yes
                  </paper-item>
````

**Comment by morbidick** [comment]
you have to set it as an attribute:
```
                  <paper-item
                    value$="[[picklistValues.ENHANCEDYESNO_YES]]">
                    Yes
                  </paper-item>
```

**Comment by dman777** [comment]
Thanks. 

Could the verbiage need refinement? the `value` is a attribute. From documentation, `$` is used for html native attributes or dynamic values. But the without the  `$`, `value` is still a attribute.

**Comment by jsilvermist** [comment]
`paper-listbox` is getting the selected attribute using:
```js
var propValue = item[dashToCamelCase(this.attrForSelected)];
return propValue != undefined ? propValue :
                                item.getAttribute(this.attrForSelected);
```
So it's getting the property first, and if it's not set it falls back to the attribute.

In this case, `value` isn't defined on `paper-item` as a property, so binding to it's attribute instead is a good way to avoid any issues with the linter, as I don't believe it should cause a linter error.
