### ISSUE TITLE
gp.sh not working for private repos

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/tools#58]
Running `gp.sh` for a non-public repository fails with the following error:

``` sh
bower my-element#master       not-cached git://github.com/my-org/my-element.git#master
bower my-element#master          resolve git://github.com/my-org/my-element.git#master
bower my-element#master          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/my-org/my-element.git", exit code of #128 fatal: remote error:    Repository not found.
```

The problem here seems to be the repository url `git://github.com/my-org/my-element.git#master` which should probably be something like `git@github.com:my-org/my-element.git`.

**Comment by rictic** [comment]
Outdated, from a previous use of this repo.
