### ISSUE TITLE
[polymer-cli] Init command creates unexpected file

### ISSUE THREAD

**Issue by lpellegr** [Polymer/tools#583]
Using polymer-cli `1.7.7`, the command `polymer init` followed by template selection `polymer-3-element` or `polymer-2-element` creates an unexpected file called `_element.{html,js}`.

Most probably, the original template is not deleted at the end of the process.

**Comment by jajaperson** [comment]
I'm getting this with `polymer-3-application` and it seems to be exactly the same as `app.js`.
