### ISSUE TITLE
Polymer build exclude file js for minify 

### ISSUE THREAD

**Issue by maxiplay** [Polymer/tools#601]
I'm using external dependency already minified. The build process create a new minfied file that break the external dependency. So I test to exclude this dependency from minification

` "js": {
        "compile": false,
        "minify": {
          "exclude": ["**.min.js"]
        }
      },
`

The feature is now not broken but it seems the file is not minified anymore.

It's a standard behavior to unminified external file imported in html import ?

**Comment by iSuslov** [comment]
Possibly related to https://github.com/Polymer/tools/issues/279
