### ISSUE TITLE
[polymer-cli] Allow running a single build instead of all builds in builds array of polymer.json

### ISSUE THREAD

**Issue by therealzteve** [Polymer/tools#606]
It would be nice if I could specify a build from the builds array in my polymer.json if I only need to build one specific build instead of all.

Reason:
We develop web applications with polymer which should run on a tomcat server. For using Polymer 3 we need to transform module specifiers to urls via the build command. The build command does build every build each time I run polymer build. This is time and resource expensive as I only need my dev build during devlopment time to rebuild.

**Comment by jsilvermist** [comment]
Agreed, I run different deploys for testing, staging, and release. Having to build all builds at once is quite a waste of time.

**Comment by Bubbit** [comment]
This is already possible:

```
$ polymer build --help

polymer build

  Builds an application-style project 

Command Options

  --name string                    The build name. Defaults to "default".                                        
  --preset string                  A preset configuration to base your build on. User-defined options will       
                                   override preset options. Optional. Available presets: "es5-bundled", "es6-    
                                   bundled", "es6-unbundled".                                                
```

By running `polymer build --name 'buildname'` you can specify which build to run. this is with cli version 1.7.2 btw, not sure if it has been broken in a later release ;)

**Comment by jsilvermist** [comment]
@Bubbit Currently that just names the build, it doesn't run a specific configuration.

**Comment by Bubbit** [comment]
@jsilvermist You're correct, for some reason I thought it has worked in the past ^^

**Comment by hyperpress** [comment]
Details: polymer-cli:   ##v1.9.7
-----------------------------------
May be related to #757  

I can confirm that using, for example: `polymer build --name es6 --preset es6-bundled` results in a correct build with _preset_ of **es6** with build _name_ **es6-bundled**. 

However, **polymer build** requires **both** options as arguments (it appears):
- Using only the `--name foo` option will result in a raw build named `foo`
- Using only the `--preset bar` option results in a raw build named `default`

This is understandably confusing as the --name option can easily be mistaken for the **polymer.json name field**, which is actually in truth the **preset name**.

I'll do a PR to clarify this in the instructions for now, but I may work on a better solution over the weekend and submit that for review as well.
 
Applicable section of polymer.json used for this test:
![polymer json](https://user-images.githubusercontent.com/25212653/54844730-908d3980-4ca5-11e9-95af-b0bec74fb42c.png)
