### ISSUE TITLE
Polymer/tools not being maintained anymore?

### ISSUE THREAD

**Issue by MaKleSoft** [Polymer/tools#61]
Seems like there hasn't been any activity here for a while. My guess is that the tools included here will be incorporated into the polymer cli at some point? I'm specifically interested in the `gp.sh` script. Will the cli implement this feature at some point?

**Comment by oneezy** [comment]
I'm curious about this also. What is the recommended way of automating this process now???

Ideally, I want to be able to `git push`, and be as lazy as possible w/ automation :grin::zzz:

1. `git push` 
2. run tests w/ Travis CI + Sauce _`(.travis.yml)`_
3. auto create demo/docs from _`(gp.sh)`_
4. go to sleep

-----

Searching around the interwebs lead me to 2 approaches (just over a year old) that take Polymer's 
[Creating Reusable Elements](https://www.polymer-project.org/1.0/docs/tools/reusable-elements) guide a step further:

1. **[How to build Polymer components with Github and Travis CI](https://medium.com/collaborne-engineering/how-to-build-polymer-components-with-github-and-travis-67683ef8bf0d#.g89761fyn)** | `Nov 20, 2015`
**By:** @ronnyroeller @collaborne

2. **[Automatic github pages deployment for Polymer elements with Travis CI](https://zisismaras.me/polymer/2015/12/02/automatic-github-pages-for-polymer-elements-with-travis-ci.html)** | `Dec 2, 2015`
**By:** @zisismaras

_Being that I'm pretty new to this whole testing and auto generating thing w/ Travis + Sauce, and also being that the Polymer Tools are evolving at a rapid pace, I'm curious on how to piece this whole thing together._

@azakus @frankiefu @addyosmani , how are y'all doing it?

**Comment by rictic** [comment]
Outdated, from a previous use of this repo.
