### ISSUE TITLE
Travis: On polylint errors the connection to Sauce Labs stays open

### ISSUE THREAD

**Issue by IchordeDionysos** [Polymer/tools#62]
In the files https://github.com/Polymer/tools/tree/master/travis
both .yml files with and without sauce labs: 
If polylint fails with an exit code of 0, the Travis build errors instead of failing, so Travis doesn't do any kind of clean up after the build because it immediately stops building. 

For example in the Travis .yml for Sauce Labs the connection stays open, so my suggestion is to move polylint from `before_script` to `script` so only the build fails and does not error.

**Comment by oneezy** [comment]
I'm curious about this too.. Is this still the recommended approach or?? 

@azakus

**Comment by rictic** [comment]
Outdated, from a previous use of this repo.
