### ISSUE TITLE
[analyzer] Property defined in the mixin constructor does not have description and type definition

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#630]
In some of the components and mixins we have property definitions like this:
```js
    constructor() {
      super();
      /**
       * Submittable string value. The default value is the trimmed text content of the element.
       * @type {string}
       */
      this.value;
    }
    get value() {
      return this._value !== undefined ? this._value : this.textContent.trim();
    }
    set value(value) {
      this._value = value;
    }
```
With latest `polymer-cli` it only works for elements, but not for mixins. 

### Before

```             
"name": "value",
"type": "string",
"description": "Submittable string value. The default value is the trimmed text content of the element.",
```

Permalink:
https://github.com/vaadin/vaadin-item/blob/699c0c8ebb89f6004aa6de5a011b0a9294a23939/analysis.json#L26

### After

```             
"name": "value",
"type": "?",
"description": "",
```

Permalink:
https://github.com/vaadin/vaadin-item/blob/bd28f0b29b3fbd977fee1c0303abde4ef4aa1d65/analysis.json#L26

Note: the same JSDoc annotation in `vaadin-checkbox` element (not mixin) working fine with the latest analyzer in polymer-cli 1.7.7: https://github.com/vaadin/vaadin-checkbox/blob/e9af82ba9b6017af03d214d3a9286018f4beab5d/src/vaadin-checkbox.html#L158

**Comment by 43081j** [comment]
FYI its because we overwrite the property when scanning the accessor.

Guess we should be merging instead of overwriting on second scan.
