### ISSUE TITLE
[analyzer] exclude life cycle methods (or make them "protected")

### ISSUE THREAD

**Issue by Scarygami** [Polymer/tools#637]
Life cycle methods like `connectedCallback`, `disconnectedCallback` etc. shouldn't show up as public methods in the element description.

```
"methods": [
  {
    "name": "connectedCallback",
    "description": "",
    "privacy": "public",
    ...
  }
]
```

They could probably be removed completely from the analyzer output, or at least marked as protected.

**Comment by 43081j** [comment]
Seeing as they're technically public (nothing stopping you from `el.connectedCallback()`), we should probably just drop them.

If we agree on that I'm up for throwing up a quick PR for it.
