### ISSUE TITLE
Broken path to bower_components directory

### ISSUE THREAD

**Issue by steltz** [Polymer/tools#653]
When I run `wct` from the root of my project, I get an error telling me to install `web-component-tester` as a dependency. However, I've already installed `web-component-tester` as a dev-dependency using Bower.

My bower_components are installed at `./public/bower_components` in my project but `wct` is looking for my bower components at `./bower_components`

Does anyone know how I can change the path of where `wct` looks for my bower components?

**Comment by barnomics** [comment]
You can try configuring your `.bowerrc` 
https://bower.io/docs/config/

```
{
  "directory": "./public/bower_components"
}
```
