### ISSUE TITLE
Cannot find module '@babel/template'

### ISSUE THREAD

**Issue by ryanwhite04** [Polymer/tools#655]
When running `polymer serve --open` I receive error
`error: [cli.main]   cli runtime exception: Error: Cannot find module '@babel/template'`
from
[`.nvm/versions/node/v10.5.0/pnpm-global/1/node_modules/.registry.npmjs.org/polymer-build/3.0.4/node_modules/polymer-build/lib/babel-plugin-dynamic-import-amd.js:17:20`](https://github.com/Polymer/tools/blob/0706809c7fba09d3923ff464e3038b93f4307e2c/packages/build/src/babel-plugin-dynamic-import-amd.ts#L18)

Polymer cli is version 1.8.0

**Comment by ryanwhite04** [comment]
I can't push the change myself, I get 
`remote: Permission to Polymer/tools.git denied to ryanwhite04.
fatal: unable to access 'https://github.com/Polymer/tools.git/': The requested URL returned error: 403`
When trying to push branch **install-babel-template**
which is understandable

**Comment by davie-robertson** [comment]
typo?
`polymer serve**r** --open`

**Comment by ryanwhite04** [comment]
Yep, typo, but the command I used was polymer serve.
The error is only if I globally install polymer-cli with pnpm, and not npm, so I think it's an issue with pnpm and not npm or polymer tools.
