### ISSUE TITLE
Upgrade to parse5

### ISSUE THREAD

**Issue by Bubbit** [Polymer/tools#656]
I'm maintaining an internal tool at my company which depends on the analyzer and after updating to the latest version (^3.1.0) I've noticed that there is a conflict between the parse5 version with the @types/parse5 version. (in version 4 of parse5 the types are inside the repository of parse5 itself and not the types that are made by someone else, breaking the code). 

The only fix I could do in order to update to this version and still use typescript for my tool was to do the same thing as the CLI: https://github.com/Polymer/tools/blob/master/packages/cli/tsconfig.json#L6 - skip type checking for dependencies (libs)

This works, but also feels a little bit bad.

Are there any plans to update to the latest version of parse5?

**Comment by aomarks** [comment]
Yes we need to update to parse5 v5, just haven't gotten the chance. In some of our packages, we deal with the typings issue by forcing the resolution we want, like this: https://github.com/Polymer/tools/blob/6a55e9455a120fbbb9e1fb4e23f041ee9fbcc0e7/packages/analyzer/tsconfig.json -- this is better than `skipLibCheck`.

Updated this issue description to track upgrading all our packages to parse5 v5.
