### ISSUE TITLE
[gen-typescript-declarations] Provide the ability to override typings

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#658]
Sometimes there isn't a good way to express a type to both closure and typescript in JS, usually because of them having different type system features.

One way of implementing this would be to allow the user to provide their own .d.ts file(s), and allow them to specify in the config file that some declarations shouldn't be generated, but instead re-exported from a pre-existing .d.ts file.

**Comment by aomarks** [comment]
You can use `excludeIdentifiers` to skip generation for something (class, method, etc.) and then `addReferences` to include another typings file, which could use module augmentation to add back the right type.

https://github.com/Polymer/tools/blob/master/packages/gen-typescript-declarations/README.md#config-options

**Comment by rictic** [comment]
Oh, nice! I'll give that a shot for typing mixinBehaviors in polymer core, see how it goes.
