### ISSUE TITLE
Fresh polymer 3 project with `es5-bundled` preset does not work with IE11

### ISSUE THREAD

**Issue by rjsteinert** [Polymer/tools#659]
I installed a fresh polymer-cli today, generated a polymer 3 app, added the `es5-bundled` preset to `polymer.json`, ran `polymer build`, then served the `es5-bundled` folder and I get the following.

![screen shot 2018-08-20 at 4 35 57 pm 1](https://user-images.githubusercontent.com/156575/44365232-31f5a800-a497-11e8-92fa-32c3b2ea07c8.png)

**Comment by rjsteinert** [comment]
I was able to get the hello world app working in IE11 by using the following build settings and then manually copying the missing `/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js` file to the build.

```
{
      "name": "es5-unbundled",
      "js": {
        "minify": false,
        "compile": "es5",
        "transformModulesToAmd": true
      },
      "css": {
        "minify": false 
      },
      "html": {
        "minify": false 
      },
      "bundle": false,
      "addServiceWorker": false,
      "addPushManifest": false,
      "preset": "es5-bundled"
    }
```

**Comment by rjsteinert** [comment]
I then copied over the missing `/node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js` and the same build now works in an up to date chrome.

![screen shot 2018-08-20 at 4 53 57 pm 1](https://user-images.githubusercontent.com/156575/44366106-ab8e9580-a499-11e8-8d2c-f7248f80e64d.png)

**Comment by rjsteinert** [comment]
No luck with this build in Firefox. Fails with `An unbalanced tree was written using document.write() causing data from the network to be reparsed.`

![screen shot 2018-08-20 at 4 55 36 pm 1](https://user-images.githubusercontent.com/156575/44366194-f6101200-a499-11e8-9619-da41f86fc2a9.png)

**Comment by rjsteinert** [comment]
Got Firefox working by manually copying over `/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce.js` into the build. 

![screen shot 2018-08-20 at 5 03 50 pm](https://user-images.githubusercontent.com/156575/44366564-12f91500-a49b-11e8-8a09-6ebb9862f5f6.png)

**Comment by jsilvermist** [comment]
In your `polymer.json`, make sure you have:

```json
  "extraDependencies": [
    "node_modules/@webcomponents/webcomponentsjs/*.js",
    "!node_modules/@webcomponents/webcomponentsjs/gulpfile.js",
    "node_modules/@webcomponents/webcomponentsjs/bundles/*.js"
  ],
```

**Comment by rjsteinert** [comment]
Ah interesting. Looking at what seems to be the templated polymer.json in the build folder, it contains references to dependencies in the `bower_components` folder. Perhaps there is some updating needed in the mechanism that generates `build/polymer.json`?

<img width="551" alt="screen shot 2018-08-20 at 6 25 07 pm" src="https://user-images.githubusercontent.com/156575/44370006-691f8580-a4a6-11e8-9925-7d7ce4d63a48.png">

**Comment by rjsteinert** [comment]
Adding those extra dependencies to the polymer.json file did the trick. I notice the reference to bower components still end up in `build/polymer.json`.

<img width="707" alt="screen shot 2018-08-20 at 6 29 49 pm" src="https://user-images.githubusercontent.com/156575/44370204-2d38f000-a4a7-11e8-86a9-6ec5068e8977.png">

**Comment by rjsteinert** [comment]
For safe keeping, this is the `polymer.json` that results in a build that works for Chrome / Firefox / and IE11.
```
{
  "npm": true,
  "lint": {
    "rules": [
      "polymer-3"
    ]
  },
  "extraDependencies": [
    "node_modules/@webcomponents/webcomponentsjs/*.js",
    "!node_modules/@webcomponents/webcomponentsjs/gulpfile.js",
    "node_modules/@webcomponents/webcomponentsjs/bundles/*.js"
  ],
  "builds": [
    {
      "name": "es5-unbundled",
      "js": {
        "minify": false,
        "compile": "es5",
        "transformModulesToAmd": true
      },
      "css": {
        "minify": false 
      },
      "html": {
        "minify": false 
      },
      "bundle": false,
      "addServiceWorker": false,
      "addPushManifest": false,
      "preset": "es5-bundled"
    }
  ]
}
```
However, when I go back to the `es5-bundled` preset and add the `extraDependencies`, that build no longer works on any of the browsers.

**Comment by rjsteinert** [comment]
Thanks for the tip @jsilvermist !
