### ISSUE TITLE
Polymer 2 element template does not update element title

### ISSUE THREAD

**Issue by wmginsberg** [Polymer/tools#66]
Hey! While testing out the 2.0 element template to get an easier start on creating an element, I noticed that the name of my element wasn't updating in my class decoration. Is this working as intended, or is it a bug? Example attached showing "MyElement" instead of "ScrabbleTile" 
<img width="591" alt="screen shot 2017-04-05 at 1 53 43 pm" src="https://cloud.githubusercontent.com/assets/4020102/24726515/8129e45c-1a07-11e7-82ce-7d9a7f38a646.png">

**Comment by FredKSchott** [comment]
This issue was moved to Polymer/polymer-cli#650
