### ISSUE TITLE
[analyzer] missing support for optional method parameters though JSDoc

### ISSUE THREAD

**Issue by jimivdw** [Polymer/tools#663]
Following the [JSDoc guide on optional parameters](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values), you should be able to specify optional parameters as follows:
```js
/**
 * My beautiful method.
 *
 * @param {string} [myparam=default] My param description
 * @returns {boolean} Something
 */
```

This is currently unsupported in the Analyzer, due to how `doctrine.parse` is called in `jsdoc.ts`. There is an option (`sloppy`, see [https://www.npmjs.com/package/doctrine#parse]) however, that would allow this. Is this way of specifying optional parameters unsupported for a reason? Or would you consider enabling the `sloppy` option?

As a side note, `doctrine` currently treats the square brackets as some sort of syntax error, which results in `myparam` and any annotations after that not being parsed at all (so from the example comment the method would only have a description; no params nor a return value).

**Comment by 43081j** [comment]
`sloppy` is horribly named by doctrine.

its actually a "turn on jsdoc3 compatibility" flag:

JSDoc3:

```
@param {string} [myparam] My param
```

Closure compiler:

```
@param {string=} myparam My param
```

I think polymer projects generally use the CC format, but im not sure if you can have default values in that.
