### ISSUE TITLE
[polymer-cli] No parser for for file type `mjs`

### ISSUE THREAD

**Issue by jajaperson** [Polymer/tools#671]
### Description
Google recommends using `.mjs` files to maintain parity with NodeJS, but `polymer-cli` apparently doesn't recognise them as javascript. When running `polymer-lint`, I got the following error:

```sh
$ polymer lint


  <script type="module" src="src/chatter-app.mjs"></script>
                            ~~~~~~~~~~~~~~~~~~~~~

index.html(66,29) error [could-not-load] - Unable to load import: No parser for for file type mjs


Found 1 error.
```

Also, I think that that error contains a typo.

### Versions & Environment

- Polymer CLI: `1.8.0`
- node: `v10.9.0`
- Operating System: `MacOS Sierra 10.12.6`

#### Steps to Reproduce
Example:

1. Create an application project: `polymer init application`
2. Rename all javascript files to use the `.mjs` convention
3. Change `import`s and `<script>` tags accordingly
3. Lint: `polymer lint`

#### Expected Results
No error is thrown

#### Actual Results
Error is throne: `index.html(66,29) error [could-not-load] - Unable to load import: No parser for for file type mjs`

**Comment by aomarks** [comment]
> Google recommends using .mjs files to maintain parity with NodeJS

Where does Google recommend this?

**Comment by web-padawan** [comment]
@aomarks there has been talk in IO, where `.mjs` has been promoted by Mathias Bynens.

**Comment by jajaperson** [comment]
https://youtu.be/mIWCLOftfRw?t=8m6s

**Comment by jajaperson** [comment]
@aomarks https://youtu.be/mIWCLOftfRw?t=8m6s

**Comment by justinfagnani** [comment]
"Google recommends"

_Some_ people at google, who I might or might not vehemently disagree with recommend this (for the sake of a non-existent Node.js feature), but I wouldn't say that _Google_ as a whole recommends it.

**Comment by justinfagnani** [comment]
@jajaperson or @web-padawan is the lack of this feature causing problems with any third party packages? I wasn't aware of too many that are actually publishing .mjs files yet.

**Comment by web-padawan** [comment]
We have tried `.mjs` in the `vaadin-router` but declined, because we realised that webpack considers it to be node-specific.

**Comment by balloob** [comment]
I use unfetch and preact with my Polymer 3 project and that ships with mjs

```
import 'unfetch/polyfill';
       ~~~~~~~~~~~~~~~~~~

src/entrypoints/compatibility.js(2,8) error [could-not-load] - Unable to load import: No parser for for file type mjs


import { render } from 'preact';
                       ~~~~~~~~

src/common/preact/unmount.js(1,24) error [could-not-load] - Unable to load import: No parser for for file type mjs
```
