### ISSUE TITLE
babel 7 types are incorrect

### ISSUE THREAD

**Issue by 43081j** [Polymer/tools#685]
I've been doing a few small PRs in babel this week (babel/babel#8627, babel/babel#8628 and babel/babel#8629) to fix or introduce their now bundled TypeScript declarations.

I noticed a few small but breaking changes between the definitelytyped types and the official babel types for Babel 7. Figured I would raise them here for you as its possible the mismatch could mean we're missing null checks etc.

By running the analyzer build against the new types, I saw these:

* Only `ObjectProperty` has a `value`, `ObjectMethod` does not ([babel-types source](https://github.com/babel/babel/blob/f6643d1804c977cc7e9f769ad24d7baeb8b9a5ed/packages/babel-types/src/definitions/core.js#L587), [example of our use](https://github.com/Polymer/tools/blob/8c2347c4bf2f6fde458a8e0e0856f8c7edd7125c/packages/analyzer/src/polymer/analyze-properties.ts#L104))
* `ArrayExpression` introduces `null` as a member ([babel-types source](https://github.com/babel/babel/blob/f6643d1804c977cc7e9f769ad24d7baeb8b9a5ed/packages/babel-types/src/definitions/core.js#L26), [example of our use](https://github.com/Polymer/tools/blob/8c2347c4bf2f6fde458a8e0e0856f8c7edd7125c/packages/analyzer/src/polymer/behavior-scanner.ts#L268))
* `ExportNamedDeclaration` has an optional declaration now ([babel-types source](https://github.com/babel/babel/blob/f6643d1804c977cc7e9f769ad24d7baeb8b9a5ed/packages/babel-types/src/definitions/es2015.js#L242), [example of our use](https://github.com/Polymer/tools/blob/8c2347c4bf2f6fde458a8e0e0856f8c7edd7125c/packages/analyzer/src/polymer/behavior-scanner.ts#L302))

I'm not sure if you guys think its important as tests pass and what not. But it means since upgrading to babel 7, we're building against incorrect types here and not handling null values in a bunch of places.

If you think its a good idea to move to babel's built in types (you _cannot_ mix and match them with the DT types, its one or the other across all babel packages), I'm happy to have a stab at it with the analyzer at least to see how it goes at some point.

cc @rictic

**Comment by rictic** [comment]
These all look like legit bugs, we should definitely upgrade
