### ISSUE TITLE
[build] [could-not-resolve-reference] - Could not resolve reference to element-mixin when using Polymer.mixinBehaviors()

### ISSUE THREAD

**Issue by andrewspy** [Polymer/tools#695]
### Description

Receive warning when building with polymer-cli v1.8.0 on polymer 2.0 project with the following class declaration:

```js
/**
 * CustomValidator
 * 
 * @polymer
 * @customElement
 * @extends Polymer.Element
 * @appliesMixin Polymer.IronValidatorBehavior
 */
class CustomValidator extends Polymer.mixinBehaviors([Polymer.IronValidatorBehavior], Polymer.Element) {
  // ...
}
```

### Steps to reproduce

N/A

### Expected result

No warning

### Actual result

Warning as follow:
```
warning [could-not-resolve-reference] - Could not resolve reference to element-mixin
```

**Comment by JaySunSyn** [comment]
Any updates on this?

**Comment by andrewspy** [comment]
Currently I am reverting to Polymer CLI v1.6 until the problem is resolved.

**Comment by JaySunSyn** [comment]
It's quite a no go if you have a big app and your pipeline fails (as it should) if there are linter errors. I'd really appreciate a fix...

**Comment by selvinfehric** [comment]
Still nothing?

**Comment by dman777** [comment]
Polymer 3 with cli 1.9.*....I am hitting this also
