### ISSUE TITLE
[esm-amd-loader] Add a hook for all-modules-loaded?

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#701]
It would be nice to have an event fire or a place to setup a callback on window.defineCompleted for that all modules are finished loading.  Would be a potentially better alternative than the wrapped calls in build's html-transform.

**Comment by usergenic** [comment]
@aomarks curious if you had thought of doing this when you wrote it?

**Comment by aomarks** [comment]
I kind of want to encourage as little special casing here as possible. There is no event for when real ES modules are finished loading, so I'd prefer we don't have one in our loader either. That way people are less likely to write forwards-incompatible code that special cased a particular behavior of this loader. You can get a notification for when all initial modules are loaded by firing an event from a `type=module` script at the end of the document, and that will work both natively and with the loader with the same timing.
