### ISSUE TITLE
[wct] `WCT.loadSuites` fails to execute tests when run inside a script type="module"

### ISSUE THREAD

**Issue by sorvell** [Polymer/tools#710]
This is only on browsers that do not natively support modules. Here's an example where the tests will not run: 

```
<script type="module">
  WCT.loadSuites([
    'shady.html'
  ]);
</script>
```

**Comment by usergenic** [comment]
Are you including the webcomponents polyfill loader?  Because you need that.

```html
    <script src="../node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
    <script src="../node_modules/wct-browser-legacy/browser.js"></script>
```

**Comment by usergenic** [comment]
I say that because WCT client code uses html imports for html suites, so most browsers will need that polyfill for loadSuites to work.
