### ISSUE TITLE
polymer-cli doesn't install on Chrome OS with Linux support (Crostini)

### ISSUE THREAD

**Issue by kenchris** [Polymer/tools#712]
![image](https://user-images.githubusercontent.com/1101339/45685526-d546e500-bb49-11e8-9a90-3e16728cfb03.png)

@justinfagnani

**Comment by kenchris** [comment]
`sudo npm install -g polymer-cli --unsafe-perm=true --allow-root` seems to work

**Comment by TimvdLippe** [comment]
You need to `chown -R $(whoami) /usr/lib/node_modules/` and never install any NPM package with sudo.

**Comment by kenchris** [comment]
All docs tell me to install polymer-cli with -g :-) eg. https://www.npmjs.com/package/@material/mwc-icon

**Comment by TimvdLippe** [comment]
Yes you should, but you should not run that command with `sudo`. E.g. instead of `sudo npm i -g polymer-cli`, always do `npm i -g polymer-cli`. To do so, you have to correct the permissions of `/usr/lib/node_modules` for which the previous command resolves that issue.

**Comment by kenchris** [comment]
yeah that of course didn't work either, so I guess the Crostini needs to make the change

**Comment by kenchris** [comment]
Anyway would be great with an error message from the installer saying what to do :)

**Comment by TimvdLippe** [comment]
They have docs on this issue: https://docs.npmjs.com/getting-started/fixing-npm-permissions
