### ISSUE TITLE
[Polymer-Cli] Security  Vulnerabilities with 1.8.0

### ISSUE THREAD

**Issue by ZheSun88** [Polymer/tools#713]
Our small project is using `"polymer-cli": "^1.8.0"` and after we run the `npm audit`, we got the  npm audit security report  which contains two HIGH level warning.

```
 High            Denial of Service

  Package         https-proxy-agent

  Patched in      >=2.2.0

  Dependency of   polymer-cli [dev]

  Path            polymer-cli > github > https-proxy-agent

  More info       https://nodesecurity.io/advisories/593
```
according to https://www.npmjs.com/package/github, this package has been renamed. 

and 
```
 High            Regular Expression Denial of Service

  Package         fresh

  Patched in      >= 0.5.2

  Dependency of   polymer-cli [dev]

  Path            polymer-cli > web-component-tester > send > fresh

  More info       https://nodesecurity.io/advisories/526
```
Can we update those?

**Comment by TimvdLippe** [comment]
This is a duplicate of #497. We are working on extracting the problematic packages from WCT. Hopefully we can finish this work soon to resolve all outstanding audit issues.
