### ISSUE TITLE
Polymer-cli complains about isIfSentence of null

### ISSUE THREAD

**Issue by kenchris** [Polymer/tools#717]
![image](https://user-images.githubusercontent.com/1101339/45810885-094a1380-bccc-11e8-9d21-971f7e28fc24.png)

This seems to be a Babel issue fixed in latest version:

https://github.com/babel/minify/issues/850

**Comment by johnthad** [comment]
I'm seeing this, too, in my app, which is based off pwa-starter-kit (though I do not see the error there or with the books PWA).

**Comment by Ludogo** [comment]
Got the same error 
`> pwa-starter-kit@0.9.0 build:prpl-server /home/***/Dev/*****
> polymer build --auto-base-path && gulp prpl-server

info:	Clearing build/ directory...
info:	(esm-bundled) Building...
info:	(es6-bundled) Building...
info:	(es5-bundled) Building...
warn:	js-transform: Unable to optimize /home/ludo/Dev/EcareMobile/src/components/my-app.js
{ err: 'Cannot read property \'isIfStatement\' of null' }
`

**Comment by usergenic** [comment]
https://github.com/Polymer/tools/pull/3388 should fix this.  Bugs in `babel-preset-minify` - disabling some of the features/plugins it uses works around this.

**Comment by usergenic** [comment]
Published polymer-build@3.1.3 and polymer-cli@1.9.8 9 days ago.  Fixed this.
