### ISSUE TITLE
[lint] Polymer lint unwanted warning for standard Polymer 3 mixins

### ISSUE THREAD

**Issue by rgladwell** [Polymer/tools#719]
### Description

Receive warning when building with polymer-cli v1.8.0 on polymer 3.0 mixin :

```js
import { dedupingMixin } from '../@polymer/polymer/lib/utils/mixin.js'

let internalMixin = (base) => class extends base {
}

export const Mixin = dedupingMixin(internalMixin)
```

The above code is written according to the official documentation for writing mixins:

https://www.polymer-project.org/3.0/docs/devguide/custom-elements#defining-mixins

### Steps to reproduce

```sh
$ git clone git@github.com:rgladwell/polymer-lint-mixin-test-case.git
$ cd polymer-lint-mixin-test-case
$ npm install
$ npm test
```
### Expected result

No warnings, as this is the documented method of writing mixins.

### Actual result

Linting warning:

```
let internalMixin = (base) => class extends base {
                                            ~~~~
mixin.js(3,45) warning [could-not-resolve-reference] - Could not resolve reference to class
```

### Workaround

Adding the following rule exclusion to `polymer.json`:

```json
{
  "lint": {
    "rules": [
      "polymer-3"
    ],
    "ignoreWarnings": ["could-not-resolve-reference"]
  }
}
```

However, this silences an important lint warning.

**Comment by sebastianroming** [comment]
I'm facing the same issue and I am not super happy with the workaround, as I generally don't want to supress all of those...
