### ISSUE TITLE
Not able to create application on Nodejs 10

### ISSUE THREAD

**Issue by MaheshKorukonda** [Polymer/tools#728]
When I tried to create polymer application using "polymer init" command, it not moving further and not asking for application name also. 
Issue while using **NodeJs** - **10.11.0**, NPM - 6.4.1 and Polymer-cli - 1.8.0 version combination.

But, at the same time with **NodeJs** - **8.12.0**, NPM - 6.4.1 and Polymer-cli - 1.8.0 version combination it able to create the polymer application.
Do we have any NodeJS version limitations for Polymer-cli?

**Comment by MaheshKorukonda** [comment]
![nodejsv10_11_0](https://user-images.githubusercontent.com/4748334/46144398-6c164e80-c27a-11e8-82fd-1be31b3b061e.PNG)
![nodejsv8_12_0](https://user-images.githubusercontent.com/4748334/46144399-6caee500-c27a-11e8-95aa-d4f950703f91.PNG)

**Comment by sebs** [comment]
9.11.2 is the one we used over wind a *NIX
