### ISSUE TITLE
babelHelpers is not defined

### ISSUE THREAD

**Issue by osamamaruf** [Polymer/tools#730]
### Polymer 2 babelHelpers is not defined error on console
Although I see babelHelpers defined in index.html of the build directory however if I run `polymer build` command and serve from the build folder `(build/es5-bundled)` I get the below console errors. 

![image](https://user-images.githubusercontent.com/34508971/46206802-aea15f00-c33e-11e8-9cf1-00409208f03e.png)

Repo for reproduction: (https://github.com/osamamaruf/babel-issue)

### Versions & Environment

- Polymer CLI:  v1.8.0
- node: v8.11.3 (Windows) ,v8.9.4 (Linux)
- Operating System: Windows 7, Ubuntu 16.04.5 LTS (Occurs only for crisped code)
- Browsers Tested on : Chrome v.69
#### Steps to Reproduce

1. Get the source code from the (https://github.com/osamamaruf/babel-issue)
2. Run `bower install`
3. Build `polymer build`
4. Build is successful
5. Serve from the build directory `polymer serve` (build/es5-bundled)
6. Errors on console.

#### Expected Results
There should not be any error and `Hello World` should be displayed on the page.

#### Actual Results
`babelHelpers is not defined` is shown on console.

#### Note
The index.js error goes away if crisping is done. However, the babel one still stays. Can share repo for this as well if required to troubleshoot. (https://github.com/osamamaruf/babel-issue/tree/crisped)
![image](https://user-images.githubusercontent.com/34508971/46207802-0b524900-c342-11e8-8bf9-627256f8a765.png)

**Comment by osamamaruf** [comment]
This issue is also mentioned in https://github.com/PolymerLabs/crisper/issues/53

**Comment by osamamaruf** [comment]
As per my understanding the reason for this is because polymer build injects the babelHelpers into the ```index.js``` file. The load order becomes: 

_index.html_
```html
<link rel="import" href="src/components/my-app/my-app.html">  // 1
.
.
.
<script src="index.js"></script>   // 3
```  

_my-app.html_
```html
<script src="my-app.js"></script> // 2
```  
i.e. the index.js file having the babelHelpers definition is loaded afterwards. As a work around by adding the ```async``` attribute to the shell import the order ```index.js``` file precedes the ```my-app.js``` and all works well.

#### Question
This has not been documented anywhere and also I think that the babelHelpers definition should be injected into the app shell and not the index file for a proper fix. For background see : https://github.com/Polymer/polymer-cli/issues/606

**Comment by jsilvermist** [comment]
@osamamaruf Injecting the helpers in the app shell instead of the entrypoint would also make it much easier to bundle elements for use on sites where you are importing an element bundle on top of an existing infrastructure.

**Comment by isilmartinez** [comment]
Any light to this matter?
I ran into the same issue and no luck so far
