### ISSUE TITLE
Customize Polymer Build Pipeline for minifying the lit html templates

### ISSUE THREAD

**Issue by phani1kumar** [Polymer/tools#732]
Is there a way to customize the polymer build pipeline and use the rollup plugin 

https://github.com/asyncLiz/rollup-plugin-minify-html-literals

to minify the css and html inside the html literals?

**Comment by moderndeveloperllc** [comment]
Might want to look into [`uglify-template-string-loader`](https://www.npmjs.com/package/uglify-template-string-loader). I've [seen it used with webpack](https://github.com/web-padawan/polymer3-webpack-starter/blob/master/webpack.config.js), but it can be used without.

**Comment by phani1kumar** [comment]
I've tried to use the babel plugin "https://github.com/goto-bus-stop/babel-plugin-template-html-minifier" suggested by @web-padawan in polymer-3 slack channel. 

To test it, I just added this as a plugin inside the `node_modules/polymer-build/lib/js-transform.js` at line number 81 as 
```
[require('babel-plugin-template-html-minifier'),{
      "modules": {
        "lit-html": ["html"],
        "@polymer/lit-element": ["html"]
      },
      "htmlMinifier": {
        "collapseWhitespace": true,
        "minifyCSS": false,
        "removeComments": false
      }
    }],
```
plain lit-html is getting minified just fine, but nested lit-htmls are failing. Looks like the plugin is not mature enough and I should wait for some more time before giving it a go again!

Or, may be approach I followed is absolutely wrong!

**Comment by phani1kumar** [comment]
Without knowing much about babel plugins, I've added following in the CallExpression method of the plugin, to make the minification work! 

```
        if(!this.added) {
          this.bindings.add(path.parentPath.scope.getBinding('html'));
          this.bindings.add(path.scope.getBinding('html'));

          this.added = true;
        }
```

I've observed, it is not picking the bindings properly and hence failing, hence added this to bypass the condition to minify!
