### ISSUE TITLE
Please add complete valid ES5 transpilation sample for polymer-build especially for Polymer 3

### ISSUE THREAD

**Issue by lawlietmester** [Polymer/tools#748]

**Comment by btopro** [comment]
https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/element/templates/polymer.json that's what we are using when kicked out from our tooling.

**Comment by lawlietmester** [comment]
@btopro I mean polymer-build in npm for gulp task, not "polymer build" command. And your code does not transpile even for "polymer build" because you wrote `"browserCapabilities": ["es2015", "modules"]`

**Comment by btopro** [comment]
ahh I see. I was going that route and ran into inconsistencies between the CLI and gulp invoking it. I needed to do this instead -- https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/element/templates/gulpfile.js#L62-L68
