### ISSUE TITLE
[wct-mocha] Clicking on a test suite in the report view redirects to the grep url, but no tests are ran

### ISSUE THREAD

**Issue by pdesjardins90** [Polymer/tools#786]
## Problem

I have this file:

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">
  <title>some-component</title>
  <script src="/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
  <script src="/node_modules/mocha/mocha.js"></script>
  <script src="/node_modules/sinon/pkg/sinon.js"></script>
  <script src="/node_modules/chai/chai.js"></script>
  <script src="/node_modules/sinon-chai/lib/sinon-chai.js"></script>
  <script src="/node_modules/dirty-chai/lib/dirty-chai.js"></script>
  <script src="/node_modules/wct-mocha/wct-mocha.js"></script>
</head>

<body>
  <script type="module">
    import { SomeComponent } from '/src/some-component.js'

    describe('some-component', () => { 
        it('does something', () => { 
            expect(SomeComponent.doSomething()).to.be.true()
        })
    })
  </script>
</body>

</html>
```

When I run WCT with wct-mocha on the folder containing this test, it runs this file and others correctly. However, when I click on its name in the reporter, I'm redirected to `
http://localhost:8081/components/@company/app/generated-index.html?cli_browser_id=0&grep=test%2Fmy-folder%2Fsome-component-test%5C.html` but no tests are ran

## Expected

It should run this file's tests normally

**Comment by mkorenko** [comment]
Having the same issue when using mocha > v3 (reproduces on the latest v5.2.0; 3.5.3 - works).
It seems the issue is in suites.ts:127 / browser.js:1391:
`mocha.grep(GREP);`
Commenting this line fixes the issue for test files filtering, but disables filtering by suites.
