### ISSUE TITLE
Cannot run compiled polymer 3 project properly which works fine with polymer serve

### ISSUE THREAD

**Issue by aktasmehmet** [Polymer/tools#790]
Description

I have a project which consists of node modules and reusable elements created by myself. Each component has its own index.html (kind of a demo page). All of these index.html pages are looking fine if I run "polymer serve" at the root level of my project. But when I try to execute "polymer build" and serve the build folder with a web server (Python SimpleHttpServer in my case), those index.html pages give errors. It will be more clear if you look at the structure below:

MyProject
-- node_modules
---- @polymer
---- @webcomponents
-- src 
---- my_components_1
------ my-foo
-------- my-foo.js
-------- index.html
------ my-foo-2
-------- my-foo-2.js
-------- index.html
---- my_components_2
------ my-foo-3
-------- my-foo-3.js
-------- index.html
------ my-foo-4
-------- my-foo-4.js
-------- index.html

All of these components are reusable and they are imported in each others definitions.

"**polymer serve**" is executed at root level:
- http://localhost:8081/src/my_components_1/my-foo/index.html is looking fine

"**polymer build**" is executed at root level (Then execute "**python -m SimpleHTTPServer**"):
- http://localhost:8000/src/my_components_1/my-foo/index.html throws error to console like: 

**Uncaught ReferenceError: define is not defined**

The built index.html files contain this line which throws the error above: 

`<script>define(['/src/my_components_1/my-foo/my-foo.js']);</script>`

I tried everything, changed the paths but no luck. In fact, I do not develop a single page app but it has to run anyway. Any help will be appreciated. Thanks.

**Comment by robertfoobar** [comment]
Hi @fenerlee1907 ,

I was having similar problems when I started with Polymer development a couple of months ago. I did some reverse engineering starting from ```polymer serve``` and finally ended up extracting polyfill and loader code that determines which browser features are supported and based on that loads either the es5 or es6 builds.

Please take a look at my boilerplate sample here: https://github.com/robertfoobar/polymer-3-web-component-sample.

Disclaimers:

- it's far from great but it works.
- this is just my pragmatic way of getting polymer into production.

**Comment by aktasmehmet** [comment]
Hi @robertfoobar ,

Thank you for the answer. After doing some research, I am now convinced that it is best to keep the folder structure in Polymer Sample project in order to make it work properly. You can also use a different structure but then there is a lot to do in polymer.json when building. 

Anyway, thank you for your guiding answer, too. I'll also use it for sure.
