### ISSUE TITLE
Polymer 3 app on build version fails : Uncaught ReferenceError: Polymer is not defined

### ISSUE THREAD

**Issue by mahdiridho** [Polymer/tools#819]
I develop an app with polymer 3 starter kit with the general structure :

```
index.html
src/
|_ my-app.js
|_ my-transaction.js
|_ my-manual.js
modules/
|_ data-transaction.js

```
index.html imports the my-app.js module like so : 
`<script type="module" src="src/my-app.js"></script>`

my-app.js imports both my-transaction and my-manual dynamically once route changes like so :
```
case 'transaction':
   import('./my-transaction.js');
   break;
case 'manual':
   import('./my-manual.js');
   break;
```

both my-transaction.js and my-manual.js import the same module data-transaction like so :
`import '../modules/data-transaction.js';`

Everything work well on development version and I can operate the app on browser correctly. Then I deploy the production version by "polymer build" and succeed. This is my polymer.json :
```
{
  "entrypoint": "index.html",
  "shell": "src/my-app.js",
  "sources": [
    "images/**/*"
  ],
  "extraDependencies": [
    "manifest.json",
    "node_modules/@webcomponents/webcomponentsjs/*.js",
    "!node_modules/@webcomponents/webcomponentsjs/gulpfile.js",
    "node_modules/@webcomponents/webcomponentsjs/bundles/*.js"
  ],
  "builds": [
    {
      "name": "es6-bundled",
      "browserCapabilities": [
        "es2015"
      ],
      "js": {
        "minify": true,
        "transformModulesToAmd": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      },
      "bundle": true,
      "addServiceWorker": true
    }
  ],
  "moduleResolution": "node",
  "npm": true,
  "lint": {
    "rules": [
      "polymer-3"
    ]
  }
}
```
When I served the build version and open the app on the browser, there is bug on the browser console with the error report like so :
![screenshot from 2018-12-19 00-02-27](https://user-images.githubusercontent.com/10230037/50155991-a9dabe80-0321-11e9-8721-cea1badfd807.png)

I checked the my-app.js on the build version refer to the error report and I got the problem from. So there's the data-transaction.js inline script on my-app.js build version. It is supposed on both my-transaction.js & my-manual.js build version, however I can't see it on them.

If I remove data-transaction.js module on my-manual.js then re-build them, It will be different results. data-transaction.js inline script can be found on my-transaction.js build version and nothing in my-app.js either my-manual.js. The interesting one, either the development and build version can be running well on browser with this solution. However I get other problem with the app js threads.

The js threads problem I mean is related to the data-transaction template which be pushed to html of both my-transaction & my-manual. So in the first time app load, my-transaction.js will bind the data-transaction property. Before the binding process completed, I change the route page to my-manual then push bind event to data-transaction property on my-manual.js. The threads run well, the properties update well, however the data-transaction layout doesn't show up on my-manual.js. To show up it, I need to go back the route page to my-transaction and back again to my-manual.

The last problem is nothing on development version of the first one which import data-transaction to both my-transaction and my-manual.

I am not sure my explanation will be clear here, so tell me where the part you lost them. I have researched this issue and seems very new. I hope you have best solution here?

Additional infos I have worked out to this issue with the following resources :
Polymer version 3
polymer-cli version 1.8.0
polymer-cli version 1.8.1
polymer-cli version 1.9.1
polymer-cli version 1.9.2

Thanks

**Comment by keanulee** [comment]
Out of curiosity, what happens if you include `import '../modules/data-transaction.js';` in my-app.js as well? Could be a bundler issue when a module is included by multiple fragments but not the shell.

**Comment by mahdiridho** [comment]
> > Out of curiosity, what happens if you include `import '../modules/data-transaction.js';` in my-app.js as well? Could be a bundler issue when a module is included by multiple fragments but not the shell.
> 
> I remove data-transaction module from both my-transaction & my-manual into my-app, then get this problem :
> ![screenshot from 2018-12-19 13-18-15](https://user-images.githubusercontent.com/10230037/50194864-dbd73980-0390-11e9-92ba-a5aeffd5d5aa.png)
> 
> I run it on development version, so I think will be same problem on build version. In polymer 2 we can do that easily, include the element either on the shell or fragments right?

I think I know the problem, but doesn't have time right now. Will do more research after my work.

Thanks

**Comment by mahdiridho** [comment]
I have to say I was not careful here when define the data-transaction properties. I have a global variable named "Polymer" which async created. There are several data-transaction properties value reference to this variable, here is the problem coming. When my-app import data-transaction, it doesn't found the "Polymer" variable (undefined).

So, I fix the problem by set the properties value on connectedCallback.

Thanks @keanulee had pointed me
