### ISSUE TITLE
6.9.1 broken, where's browser.js?!

### ISSUE THREAD

**Issue by mg80** [Polymer/tools#827]
https://registry.npmjs.org/web-component-tester/-/web-component-tester-6.9.1.tgz

Where's browser.js??

Compared to: https://registry.npmjs.org/web-component-tester/-/web-component-tester-6.9.0.tgz

**Comment by nicojs** [comment]
Yep... 


![](https://memegenerator.net/img/instances/29527312/and-its-gone.jpg)

**Comment by keanulee** [comment]
Fixed in web-component-tester@6.9.2 and polymer-cli@1.9.4 (#833). Thanks for bearing with us!
