### ISSUE TITLE
Assignment of output of `Polymer({})` call generates wrong class and interface

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/tools#837]
In the definition of `paper-scroll-header-panel`, there is an additional assignment to `Polymer.PaperScrollHeaderPanel` like so:

```js
Polymer.PaperScrollHeaderPanel = Polymer({
...
});
```

This generates the following typings:

```ts
class PaperScrollHeaderPanel extends Polymer.Element {
...
}
interface PaperScrollHeaderPanel extends Polymer.IronResizableBehavior {
}
```

Note that the class has all the properties, but the `interface` does not. Instead, the interface should not be generated and the class should extend `Polymer.IronResizableBehavior`.

Part of https://github.com/Polymer/gen-typescript-declarations/issues/79

**Comment by aomarks** [comment]
I don't think this is a bug. The interface declaration augments the class interface in order to declare that the class also has properties from that behavior interface (so, the interface *does* have all the properties you see in the class declaration).
