### ISSUE TITLE
Add field for files/directories to ignore when linting

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#855]

**Comment by aomarks** [comment]
@alvardsoler commented on Jul 19, 2018

> what about this?
> this isn't working for me with this configuration:
> ` "lint": { "filesToIgnore": ["dist/**/*"], "rules": ["polymer-1"], "ignoreWarnings": [ "databind-with-unknown-property", "undefined-elements" ] },`
> I tried to find other issue but this a little confusing...
