### ISSUE TITLE
Move higher-level configuration parsing & validating out of shared config?

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/tools#857]
I'm not sure if we have a good enough reason to make this change yet, or even if we want to make this change, but I wanted to start this issue to track the conversation if things change.

## Background 
Currently PolymerProjectConfig is responsible for the parsing and validation of two, high-level configurations: "build" and "lint". Each of these is read and understood by only a single tool (Polymer CLI). 

The path we're currently on is to continue to add all config parsing responsibilities to PolymerProjectConfig. Just today I added more logic to the "build" property parser to handle presets.

The question is: should the shared PolymerProjectConfig class, responsible for all polymer.json parsing, be responsible for parsing & validating these higher-level config formats that are only used by a single other tool? Or, should that tool be responsible for it?

#### Reasons to keep in PolymerProjectConfig
- One shared place to define, parse, and validate configuration. 
- Configuration can't mean different things to different tools.
- 3rd party tooling can still define "unsupported" configurations which are simply propagated to PolymerProjectConfig (but not parsed or validated in any way).

#### Reasons to move to Polymer CLI
- `config.validate()` currently validates the entire polymer.json. That means that even an unrelated issue can stop a validating program from running (ex: `polymer lint` will fail validation if there's an issue in one of the build configs).
- Not having to parse or validate unrelated configuration = better performance.
- Tools will be able to interpret the user-provided configuration, instead of the parsed configuration (ex: a build preset is applied at parse time, so a tool would never be able to see what was set by the user vs. the preset).

/cc @rictic @usergenic @justinfagnani who have all touched this file in some way.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
