### ISSUE TITLE
Move @types dependencies to devDependencies

### ISSUE THREAD

**Issue by freshp86** [Polymer/tools#862]
Do the following deps need to be in the "dependencies" section of package.json? Can they be moved to "devDependencies" instead?

```
"@types/clone": "^0.1.29",
"@types/node": "^4.0.30",
"@types/parse5": "^2.2.32"
```

This will reduce the code being downloaded when someone depends on dom5.

**Comment by simonbuchan** [comment]
(Apologies for the necro) 

> The issue we're running into are type conflicts when running our webpack based builds that include this lib. Since our project uses webpack, we import the type definitions for wepack-env, instead of node. However, since both `wepack-env.d.ts` and `node.d.ts` declare some of the same names (ex. `require`), we get duplicate/conflicting declaration errors when compiling.
> 
> I would think this would also be an issue when a different version of a common dependent library is needed by the app. Say, for example, our app needs to use type definitions for `parse5@3.0.1`. Since `dom5` already includes a type-def for this library in it's distribution which gets installed in the "special" `@types` folder, this would cause TypeScript duplicate identifier errors.

A lot of the time this is a poor interaction between the flat node_modules structure used by default by npm (post v3) and yarn, and the default behavior of typescript to pick up all ambient types in `node_modules/@types`. You should be able to work around it by not having flattened packages ([npm's global-style](https://docs.npmjs.com/misc/config#global-style) or using [pnpm](https://pnpm.js.org)), or [explicitly listing the ambient type packages to load](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types).
