### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by stramel** [Polymer/tools#879]
Tool doesn't appear to run on windows. Ran fine on my linux PC though.

**Comment by nakcyber** [comment]
This is still an issue.

**Comment by nakcyber** [comment]
> Worked using the `windows-paths` branch for me.
> 
> **Steps that worked for me**
> 
> * clone `Polymer/gen-typescript-declarations`
> * check out `windows-paths` branch
> * run `npm i`
> * run `npm run build`
> * run `npm i -g .` to install globally the local version
> * clone `PolymerElements/iron-dropdown`
> * run `bower i`
> * run `gen-typescript-declarations --deleteExisting --outDir .`
> 
> Didn't need the `NODE_OPTIONS` set. Ran in less than 30 seconds.

Do you have a branch `windows-paths`  link on `Polymer/gen-typescript-declarations` ?
