### ISSUE TITLE
Allow customizing bower component directory

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#895]
_From @aaronanderson on April 29, 2017 17:22_

In my project I have edited the .bowerrc file to set the bower directory to assets rather than bower_components. When I open up my Polymer 2.0 components in Atom all of my imports have Linter errors due to the insertion of a reference to a non-existent bower_components directory.

Example Import in file  /home/dev/git/my-app/src/main/webapp/ui/my-app.html: 

<link rel="import" href="../assets/polymer/polymer-element.html">

Example Linter error:
Error	polymer-ide	Unable to load import: ENOENT: no such file or directory, open '/home/dev/git/my-app/src/main/webapp/ui/bower_components/assets/polymer/polymer-element.html'

This directory does not exist but /home/dev/git/my-app/src/main/webapp/assets/polymer/polymer-element.html does and the app works fine with polymer serve. 

I am using Atom 1.16.0 and polymer-ide version 0.3.0.

_Copied from original issue: Polymer/atom-plugin#58_

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
