### ISSUE TITLE
configuring parser used for linting javascript

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#896]
_From @elf-pavlik on October 28, 2017 21:42_

I would like to have similar option as in js-standard linter to use `babel-eslint` https://github.com/standard/standard#how-do-i-use-experimental-javascript-es-next-features

_Copied from original issue: Polymer/atom-plugin#67_

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
