### ISSUE TITLE
Unclosed tag is incorrectly parsed by parse5, causing trouble for autocompletion

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/tools#912]
The test below currently fails, because `parse5` returns an ast of the document completely ignoring the `<pape`. There is not even a textnode for this text. As a result of this node being removed, autocompletion does not work on unclosed tags. Instead, it removes various text nodes, which are not added to the ast which is passed to `getLocationInfoForPosition`.

In Atom what currently does work is that the `AutoCompleter` returns all results. When a user continues typing (e.g. `<pape`), the `AutoCompleter` requests new Autocompletions from the editor-service. However the editor-service refreshed its document and now has lost the autocompletions. Therefore no more autcompletions are returned to Atom causing Autocompletion to halt.

This can also be reproduced with the Atom plugin when typing `<slot-`. After the `-` the autocompletion completely halts.

```js
  test.only('works with an unclosed starttag', () => {
    const allKindsSpaceSeparated = getAllKindsSpaceSeparated(`
<!-- c -->
<pape`);
    assert.equal(allKindsSpaceSeparated, 'text text comment comment comment comment comment comment comment comment comment text text tagName tagName tagName tagName');
  });
```

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
