### ISSUE TITLE
plugin for vim

### ISSUE THREAD

**Issue by webdesus** [Polymer/tools#913]
Hi @rictic i wrote [plugin  for vim ](https://github.com/webdesus/polymer-ide.vim).  I will not be against if you fork my repository to Polymer or add link in readme. But i think better will be made fork. A little bit later i will add in readmy own plugin screenshots and gifs.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.

**Comment by webdesus** [comment]
I think this issue not important in the current moment. Cuz LSP very strong right now and correctly will be using LSP plugin for vim/neovim

**Comment by RoXuS** [comment]
Hi @webdesus, for me it doesn't work with vim-lsp + nvim + polymer 3.
My conf:
```
au User lsp_setup call lsp#register_server({
    \ 'name': 'polymer-editor-service',
    \ 'cmd': {server_info->[&shell, &shellcmdflag, 'polymer-editor-service']},
    \ 'whitelist': ['javascript'],
    \ })
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
```
It can resolve ES6 import with scoped package like 
```javascript
import { PolymerElement } from '@polymer/polymer/polymer-element.js';
```
The error:
`Cannot resolve module specifier with resolution algorithm: none`

**Comment by webdesus** [comment]
@RoXuS right now i not using Polymer in my work. Last version i used it's was Polymer 2 and all work perfect.

**Comment by RoXuS** [comment]
@webdesus arf ok, thx for your response 👍
