### ISSUE TITLE
Feature request: complete behaviors/mixins

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#919]
> @jay8t6 reported at https://github.com/Polymer/atom-plugin/issues/34

> It would be nice if the editor plugins auto populates the mixins available based on the html imports.

For Polymer 1.0 we'd just need to notice that you're in a behaviors section of a Polymer declaration.

For Polymer 2.0 we could instead let a general purpose code completion system like tern or typescript handle this, we'd just need to handle explaining the html imports graph to it.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
