### ISSUE TITLE
Editing .env file in project root and vscode plugin reported error

### ISSUE THREAD

**Issue by akc42** [Polymer/tools#920]
I have a dot-env file in my project route (`.env`) which I started to edit.  vscode polymer-ide plugin reported following error

```
[Error - 23:47:38] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: No parser for for file type 
  Code: -32603 
```

this.env file is full of assignments like

MY_PCODE=xxx

It occurs as I start to edit one of these

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
