### ISSUE TITLE
When a file that didn't exist suddenly does, we still report it as missing

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#925]
e.g. if you have imports into a bower directory but you haven't run `bower install` yet, your editor will report that the files are missing until you restart it because we cache that these files don't exist.

One elegant solution I've noticed that typescript uses to handle this efficiently is to recheck imports whenever a new import is added to the document. Alternatively, we could use something like `chokidar` to watch the filesystem and respond appropriately to changes. We could also expose the `_clearCaches` method in editors for this use case, but I would very much like to avoid this if possible, or at least only use it as a last ditch option.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
