### ISSUE TITLE
Provide intellisense / go to definition for event handlers

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#926]
> Originally filed by @bahrus at https://github.com/Polymer/vscode-plugin/issues/20

Pretty self explanatory, but <my-component on-click="

At that point, would be great if it could fine all methods and provide autocomplete. And to be able to F12 on an existing method and jump to the code.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
