### ISSUE TITLE
Can't find remote resources (e.g. absolute urls)

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#933]
> Moved from https://github.com/Polymer/vscode-plugin/issues/3#issue-181026839

gives red squiggly under href of linked stylesheets:
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700">`

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
