### ISSUE TITLE
It would be nice if ../ always meant "look at the bower directory"

### ISSUE THREAD

**Issue by rictic** [Polymer/tools#934]
> Migrated from https://github.com/Polymer/atom-plugin/issues/3
> On September 29th, 2016, @notwaldorf said:

Context: if you have an enormous folder with a billion elements in it because you work on Polymer Elements and that's how you cope, auto-complete looks at the sibling directories rather than the bower deps, which may be woefully out of date.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
