### ISSUE TITLE
Make SELENIUM_OVERRIDES available to override from base package.json

### ISSUE THREAD

**Issue by philippw** [Polymer/tools#953]
I'm trying to convince wct-local to download selenium and its drivers via an internal Artifactory server instead of directly from GitHub. selenium-standalone supports this via its baseURL settings.

However, as selenium-standalone is a transitive dependency of wct-local I cannot override the default values.
Fortunately, there's the scripts/postinstall.js and its SELENIUM_OVERRIDES, which would allow for excatly that, would it not be the case that it only ever parses settings fromwct-local's ownpackage.json`.

Can we change the lookup path from ../package.json to ../../../package.json to be able to override the Selenium settings from the base package.json?

Bug migrated from the [web-component-tester issues](https://github.com/Polymer/web-component-tester/issues/675).

**Comment by osamamaruf** [comment]
@aomarks  This issue can be closed as PR [#704](https://github.com/Polymer/tools/pull/704) fixed it.
